window.MANUAL_ANALYSES=window.MANUAL_ANALYSES||{};
Object.assign(window.MANUAL_ANALYSES,{
"1":{
 titleVerse:false,
 sources:["A Medida do Louvor, cap. 24","Texto Massorético","Calvino, Comentário dos Salmos 1–35","NET Bible Notes, apoio linguístico"],
 steps:[
 {n:1,label:"Confira o texto que será estudado",technical:"Texto e variantes",body:"O Salmo 1 não tem título no hebraico. O Texto Massorético é estável e não há variante importante que mude a mensagem. A leitura deve conservar palavras-chave como ‘caminho’, ‘lei/instrução’, ‘plantada’, ‘palha’ e ‘conhece’. A referência dos versículos nesta página segue a numeração usada na ARA.",items:["O verbo de ‘meditar’ descreve uma recitação baixa e repetida, não apenas pensamento silencioso.","‘Plantada’ é forma passiva: a imagem sugere que a árvore foi colocada junto às águas, e não que se estabeleceu ali sozinha."]},
 {n:2,label:"Ouça o Salmo como poesia hebraica",technical:"Leitura e cantilação",body:"Ouça três vezes prestando atenção à abertura longa do v. 1, à expansão do v. 3 e ao corte brusco de ‘não são assim os ímpios’ no v. 4. O som ajuda a perceber que o poema não dá o mesmo peso aos dois caminhos.",items:["Na primeira leitura, acompanhe apenas o texto.","Na segunda, marque as pausas.","Na terceira, note repetições e mudanças de ritmo."]},
 {n:3,label:"Veja onde cada verso se divide",technical:"Cólons e acentos",body:"A divisão poética é especialmente clara: o v. 1 tem três partes; o v. 2 tem duas; o v. 3 se abre em quatro partes; os vv. 4–6 voltam a unidades mais curtas. Essa forma já mostra a progressão do justo e o contraste com o ímpio.",items:["v. 1: três movimentos — andar, parar, sentar.","v. 2: prazer na instrução // meditação contínua.","v. 3: árvore, fruto, folha, prosperidade — a imagem é deliberadamente expandida.","vv. 4–6: o lado do ímpio é mais curto e termina em juízo."]},
 {n:4,label:"Confirme se essas divisões fazem sentido",technical:"Sintaxe e paralelismo",body:"As divisões são confirmadas pela gramática. No v. 1, três verbos e três ambientes formam uma progressão. No v. 2, primeiro aparece uma disposição interior e depois um hábito. No v. 3, a árvore é o sujeito de uma cadeia de resultados. No v. 6, os dois caminhos são colocados lado a lado para o veredito final.",items:["andar → deter-se → assentar-se mostra crescente fixação no mal.","prazer → meditar mostra coração e prática unidos.","caminho dos justos // caminho dos ímpios prepara o juízo final."]},
 {n:5,label:"Observe o ritmo e as mudanças de tamanho",technical:"Escansão",body:"O padrão é relativamente estável, mas os desvios carregam sentido. O v. 1 abre solenemente; o v. 3 é a maior expansão do poema; a primeira parte do v. 4 é a mais curta e funciona como um golpe: ‘não assim’. O salmo volta ao equilíbrio no v. 6.",items:["A bênção recebe mais espaço que a ruína.","O ímpio é comparado à palha e também recebe, formalmente, pouco espaço.","O ritmo serve ao contraste, não a um esquema métrico rígido."]},
 {n:6,label:"Veja como uma linha responde à outra",technical:"Paralelismo",body:"Cada verso avança, em vez de apenas repetir. O v. 1 progride da influência para a identificação; o v. 2 passa do prazer para a prática; o v. 3 passa da origem da árvore aos seus efeitos; o v. 4 contrasta árvore e palha; o v. 5 transforma a fragilidade do ímpio em incapacidade de permanecer no juízo; o v. 6 explica por que os destinos são diferentes.",items:["v. 1: progressão crescente.","v. 2: estado interior → ação contínua.","v. 3: causa providencial → fruto → permanência → resultado.","v. 4: contraste abrupto.","v. 5: juízo → exclusão da assembleia dos justos.","v. 6: conhecimento pactual de Deus → perdição do caminho oposto."]},
 {n:7,label:"Perceba as repetições e imagens importantes",technical:"Recursos poéticos",body:"O salmo trabalha com dois caminhos, árvore e palha, bênção e perdição. A palavra ‘caminho’ aparece no início e no fim, formando uma moldura. Há ainda a progressão andar–parar–sentar e o contraste entre estabilidade e dispersão.",items:["Imagem da árvore: vida recebida, alimentada e frutífera.","Imagem da palha: ausência de peso e permanência.","Inclusão com ‘caminho’: o tema do percurso moral fecha o poema."]},
 {n:8,label:"Separe os grandes blocos",technical:"Estrofes",body:"A divisão mais segura tem três blocos, confirmados por assunto, contraste e vocabulário.",items:["vv. 1–3 — o justo: o que evita, o que ama e no que se torna.","vv. 4–5 — o ímpio: o que ele é e o que não consegue fazer diante do juízo.","v. 6 — o veredito de Deus sobre os dois caminhos."]},
 {n:9,label:"Veja o desenho do Salmo inteiro",technical:"Macroestrutura",body:"O salmo funciona como um contraste centrado na virada do v. 4: justo → ‘não assim’ → ímpio → veredito. A palavra ‘caminho’ emoldura o poema e o v. 6 coloca os dois caminhos lado a lado.",items:["A: vv. 1–3 — justo.","Eixo: v. 4a — ‘não assim’.","A’: vv. 4b–5 — ímpio.","Fecho: v. 6 — Deus conhece um caminho; o outro perece."]},
 {n:10,label:"Note o que foge do padrão",technical:"Desvios significativos",body:"Três desvios merecem peso interpretativo porque coincidem com mudanças claras de assunto: o tricolo do v. 1, a expansão do v. 3 e a contração do v. 4a. Eles reforçam, respectivamente, a solenidade da escolha, a riqueza da vida do justo e o corte da condição do ímpio.",items:["Não atribuir significado espiritual a cada diferença de uma sílaba.","O desvio vale quando forma e sentido apontam na mesma direção."]},
 {n:11,label:"Resuma a mensagem em uma frase",technical:"Proposição",body:"A pessoa que rejeita o caminho do mal e recebe com prazer a instrução de Deus é sustentada por ele para uma vida frutífera e duradoura, enquanto o caminho do ímpio não tem peso para permanecer diante do juízo."},
 {n:12,label:"Coloque o Salmo no conjunto da Bíblia",technical:"Situação canônica e cristológica",body:"Salmos 1 e 2 formam a entrada do Saltério: a instrução de Deus e o Rei ungido aparecem juntos. Uma leitura reformada evita dois erros: não transforma o Salmo 1 em simples ‘seja uma pessoa melhor’, nem afirma que somente Cristo está em vista e o crente nada tem a aprender. Cristo é o justo perfeito; unidos a ele, os crentes recebem nova vida e são chamados a andar no caminho da obediência como fruto da graça.",items:["Contexto canônico: Torá e Rei abrem o Saltério.","Cristo cumpre perfeitamente a justiça que o salmo descreve.","A obediência do crente é consequência da união com Cristo, não base do favor de Deus."]}
 ],
 theology:["A lei de Deus é dom da aliança e alimento do povo, não caminho de autojustificação.","A perseverança do justo é descrita como vida recebida e sustentada por Deus.","Juízo e graça aparecem juntos: Deus conhece pactualmente o caminho dos justos.","Santificação não é moralismo autônomo; nasce da graça e produz fruto real."],
 sermon:{idea:"Deus sustenta o caminho de quem recebe sua Palavra, mas o caminho sem Deus não permanece.",need:"Somos inclinados a buscar direção, identidade e segurança no conselho de um mundo que não pode nos sustentar no juízo.",movements:[{title:"Escolha de quem ouvir",vv:"vv. 1–2",point:"A vida começa no que recusamos como conselho e no que recebemos como Palavra."},{title:"O que Deus faz com quem alimenta",vv:"v. 3",point:"A estabilidade do justo é fruto do plantio e do cuidado de Deus."},{title:"Dois caminhos diante do juízo",vv:"vv. 4–6",point:"A diferença final não é aparência presente, mas o veredito de Deus."}],climax:"‘Não assim os ímpios’ (v. 4) — a virada que separa os dois destinos.",gospel:"Jesus é o justo perfeito e o Rei do Salmo seguinte; nele somos justificados e, por seu Espírito, aprendemos a viver a justiça que o texto descreve.",applications:["examinar quais vozes moldam nossas decisões","transformar leitura bíblica em meditação constante","buscar fruto como resultado da graça, não como moeda de mérito"]}
},
"2":{
 titleVerse:false,
 sources:["Texto Massorético","Calvino, Comentário dos Salmos 1–35","NET Bible Notes","Atos 4; 13; Hebreus 1; 5 como interpretação apostólica"],
 steps:[
 {n:1,label:"Confira o texto que será estudado",technical:"Texto e variantes",body:"O Salmo 2 também não tem título no hebraico. O texto é estável no conjunto, mas o v. 12 exige cuidado: a expressão tradicionalmente traduzida por ‘beijai o Filho’ contém a palavra aramaica bar, incomum nesse contexto. A leitura messiânica do salmo não depende desse único detalhe; ela é firmada pelo tema régio do poema e, sobretudo, pelo uso explícito que o Novo Testamento faz dele.",items:["Não construir a cristologia apenas sobre a tradução de v. 12.","O decreto do v. 7 é o centro textual que o NT aplica diretamente a Cristo."]},
 {n:2,label:"Ouça o Salmo como poesia hebraica",technical:"Leitura e cantilação",body:"Ouça as mudanças de voz. Primeiro falam as nações; depois Deus; em seguida o rei; por fim a voz de advertência se volta aos governantes. O efeito dramático é essencial: o salmo é quase uma cena de tribunal e entronização."},
 {n:3,label:"Veja onde cada verso se divide",technical:"Cólons e acentos",body:"Os versos são majoritariamente formados por duas linhas que se completam. As grandes fronteiras não dependem apenas do ritmo, mas das mudanças de personagem e de discurso direto.",items:["vv. 1–3: rebelião das nações.","vv. 4–6: resposta soberana de Deus.","vv. 7–9: decreto proclamado pelo rei.","vv. 10–12: chamado à submissão e ao refúgio."]},
 {n:4,label:"Confirme se essas divisões fazem sentido",technical:"Sintaxe e paralelismo",body:"A gramática confirma quatro cenas. Os imperativos dos rebeldes em v. 3 contrastam com o decreto divino em vv. 6–7. O rei não toma o trono por conquista pessoal: ele recebe um decreto e uma herança. No final, os próprios reis rebeldes recebem imperativos de prudência, serviço e submissão."},
 {n:5,label:"Observe o ritmo e as mudanças de tamanho",technical:"Escansão",body:"O ritmo acompanha a tensão dramática, mas não forma um metro rígido. As partes de fala direta tendem a ganhar peso. O ponto a observar é menos uma contagem isolada e mais a passagem crescente: conspiração humana → riso divino → decreto → advertência."},
 {n:6,label:"Veja como uma linha responde à outra",technical:"Paralelismo",body:"O paralelismo frequentemente intensifica a cena.",items:["vv. 1–2: povos → reis e governantes; agitação difusa → conspiração organizada.","v. 3: romper laços → lançar cordas; rejeição completa da autoridade.","vv. 4–5: Deus ri → Deus fala em ira; desprezo soberano → juízo.","vv. 7–9: Filho → herança das nações → governo sobre elas.","vv. 10–12: aprender → servir → refugiar-se; a ameaça termina em convite de graça."]},
 {n:7,label:"Perceba as repetições e imagens importantes",technical:"Recursos poéticos",body:"O salmo usa contraste de tronos: a terra conspira, mas o céu já decidiu. ‘Ungido’, ‘Filho’, ‘nações’, ‘reis’ e ‘refúgio’ formam o vocabulário central. O final retoma a palavra ‘bem-aventurados’ do Salmo 1 e liga os dois poemas."},
 {n:8,label:"Separe os grandes blocos",technical:"Estrofes",body:"Quatro blocos de três versículos formam uma estrutura extremamente clara.",items:["vv. 1–3 — rebelião humana.","vv. 4–6 — reação e decreto de Deus.","vv. 7–9 — palavra do rei ungido.","vv. 10–12 — chamado aos governantes."]},
 {n:9,label:"Veja o desenho do Salmo inteiro",technical:"Macroestrutura",body:"O salmo progride de rebelião para entronização e termina em decisão. O centro não é o poder das nações, mas o decreto de Deus. A última palavra temática é refúgio: o Rei que julga também é o lugar para onde os rebeldes são chamados a fugir."},
 {n:10,label:"Note o que foge do padrão",technical:"Desvios significativos",body:"A principal mudança é a troca de vozes. Cada mudança redefine a cena: os homens falam como se fossem livres; Deus responde como soberano; o rei fala como herdeiro; o pregador do salmo chama os rebeldes à sabedoria. Essa sequência, e não numerologia, é o desvio interpretativamente decisivo."},
 {n:11,label:"Resuma a mensagem em uma frase",technical:"Proposição",body:"A rebelião das nações não pode desfazer o decreto de Deus: ele estabeleceu seu Rei, entregou-lhe as nações e chama os próprios rebeldes a abandonar a resistência e encontrar refúgio no Filho."},
 {n:12,label:"Coloque o Salmo no conjunto da Bíblia",technical:"Situação canônica e cristológica",body:"Este é um salmo régio com horizonte davídico real, mas o Novo Testamento identifica o seu cumprimento pleno em Jesus. Atos 4 aplica a rebelião das nações à oposição contra Cristo; Atos 13 e Hebreus 1 e 5 usam o decreto ‘Tu és meu Filho’. A leitura reformada começa no rei davídico e segue a própria Escritura até o Messias, sem transformar detalhes em alegorias.",items:["Não aplicar a promessa a qualquer governo ou nação cristianizada.","O domínio universal pertence ao Messias.","A resposta do ouvinte é arrependimento, temor reverente e refúgio em Cristo."]}
 ],
 theology:["A soberania de Deus não reage nervosamente à história; ela governa a história.","A aliança davídica encontra seu Rei definitivo em Cristo.","Juízo e evangelho se encontram no mesmo Rei: ele quebra a rebelião e acolhe quem nele se refugia.","A igreja anuncia o reinado de Cristo; não toma para si o poder político do Messias."],
 sermon:{idea:"Deus já estabeleceu o Rei que nenhuma rebelião consegue derrubar, e a única resposta sábia é refugiar-se nele.",need:"Queremos autonomia diante de Deus e tratamos seus limites como correntes.",movements:[{title:"A ilusão da autonomia",vv:"vv. 1–3",point:"A rebelião humana é organizada, mas continua sendo rebelião contra o Criador."},{title:"O decreto que não pode ser cancelado",vv:"vv. 4–9",point:"O trono do Messias depende da palavra de Deus, não do consentimento das nações."},{title:"A graça da advertência",vv:"vv. 10–12",point:"Antes do juízo final, reis e povos ainda são chamados a aprender, servir e buscar refúgio."}],climax:"‘Eu constituí o meu Rei sobre Sião’ (v. 6) e o decreto do Filho (v. 7).",gospel:"Jesus é o Filho entronizado, crucificado por governantes rebeldes e ressuscitado por Deus; o Rei contra quem pecamos é também aquele em quem somos convidados a refugiar-nos.",applications:["abandonar a fantasia de autonomia","submeter poder e decisões ao senhorio de Cristo","anunciar o evangelho inclusive a quem hoje resiste ao Rei"]}
},
"3":{
 titleVerse:true,
 sources:["Texto Massorético","2 Samuel 15–18","Calvino, Comentário dos Salmos 1–35","A Medida do Louvor, princípios de lamento e Selâ"],
 steps:[
 {n:1,label:"Confira o texto que será estudado",technical:"Texto e variantes",body:"A sobrescrição situa o salmo na fuga de Davi diante de Absalão. Ela é parte importante da leitura histórica: o rei ungido está expulso de Jerusalém e cercado por gente que conclui que Deus o abandonou. Não há variante textual principal que altere essa linha de interpretação."},
 {n:2,label:"Ouça o Salmo como poesia hebraica",technical:"Leitura e cantilação",body:"Ouça os três Selás como pausas possíveis. O salmo começa com vozes inimigas, passa à confissão de quem Deus é, desacelera no sono tranquilo e termina em clamor e bênção sobre o povo."},
 {n:3,label:"Veja onde cada verso se divide",technical:"Cólons e acentos",body:"As divisões principais acompanham quatro movimentos: ameaça, confiança, descanso e oração. As pausas marcadas por Selâ ajudam, mas não são usadas sozinhas para decidir a estrutura.",items:["vv. 1–2 — muitos inimigos e a acusação de que não há salvação.","vv. 3–4 — Deus como escudo, glória e resposta.","vv. 5–6 — sono e ausência de medo.","vv. 7–8 — pedido de ação e confissão de que a salvação pertence ao Senhor."]},
 {n:4,label:"Confirme se essas divisões fazem sentido",technical:"Sintaxe e paralelismo",body:"A mudança de ‘muitos dizem’ para ‘tu, Senhor’ é o primeiro grande giro. Depois, os verbos ‘deitei-me, dormi, acordei’ descrevem uma experiência concreta de preservação. No fim, os imperativos ‘levanta-te’ e ‘salva-me’ retornam à oração direta."},
 {n:5,label:"Observe o ritmo e as mudanças de tamanho",technical:"Escansão",body:"A forma é relativamente compacta. O sentido principal está na alternância de vozes e na pausa entre ameaça e confiança. O descanso dos vv. 5–6 funciona quase como centro emocional: a crise não acabou, mas o salmista consegue dormir porque atribui sua sustentação a Deus."},
 {n:6,label:"Veja como uma linha responde à outra",technical:"Paralelismo",body:"O poema avança em pares claros.",items:["vv. 1–2: número de inimigos → interpretação teológica errada deles.","vv. 3–4: quem Deus é para Davi → o que Deus faz ao ouvi-lo.","vv. 5–6: sono preservado → coragem diante de milhares.","vv. 7–8: pedido por salvação → confissão de que a salvação é de Deus → bênção ao povo."]},
 {n:7,label:"Perceba as repetições e imagens importantes",technical:"Recursos poéticos",body:"As imagens centrais são o escudo ao redor, a cabeça levantada e o santo monte. A linguagem de guerra termina em linguagem de bênção. O salmo também inverte a afirmação dos inimigos: eles dizem ‘não há salvação’; o final responde ‘do Senhor é a salvação’."},
 {n:8,label:"Separe os grandes blocos",technical:"Estrofes",body:"Quatro blocos curtos descrevem uma trajetória espiritual sem ocultar a ameaça.",items:["vv. 1–2 — diagnóstico da crise.","vv. 3–4 — confissão de fé.","vv. 5–6 — repouso sustentado por Deus.","vv. 7–8 — pedido de libertação e bênção comunitária."]},
 {n:9,label:"Veja o desenho do Salmo inteiro",technical:"Macroestrutura",body:"A pergunta ‘há salvação para ele?’ é respondida pelo próprio fechamento: ‘do Senhor é a salvação’. Entre essas duas frases, o salmista mostra como a fé atravessa a noite. A estrutura vai da interpretação dos inimigos para o veredito de Deus."},
 {n:10,label:"Note o que foge do padrão",technical:"Desvios significativos",body:"O elemento mais marcante não é uma contagem, mas a tranquilidade inesperada no centro do perigo. Dormir no meio da revolta funciona como sinal concreto de confiança. O salto final do indivíduo para ‘o teu povo’ também amplia o salmo: a restauração do rei importa à comunidade pactual."},
 {n:11,label:"Resuma a mensagem em uma frase",technical:"Proposição",body:"Quando muitos interpretam a crise como prova de abandono, o crente pode descansar porque Deus é seu escudo, ouve sua oração e conserva em suas próprias mãos a salvação do rei e do povo."},
 {n:12,label:"Coloque o Salmo no conjunto da Bíblia",technical:"Situação canônica e cristológica",body:"Historicamente, o salmo nasce da rejeição de Davi durante a revolta de Absalão. Isso cria um padrão do rei ungido rejeitado, preservado e restaurado, que encontra sua forma perfeita no Filho de Davi. O salmo não é uma profecia direta de cada detalhe da paixão, mas a igreja pode orá-lo em Cristo, o Rei rejeitado que venceu a morte e sustenta seu povo.",items:["Ler primeiro à luz de 2 Samuel 15–18.","Não transformar ‘deitar e acordar’ em previsão direta da ressurreição.","Aplicar a confiança ao crente unido ao Rei ressuscitado."]}
 ],
 theology:["A providência de Deus pode dar repouso antes de remover a ameaça.","A salvação pertence ao Senhor, não à força do rei nem ao tamanho do exército.","O cuidado com o indivíduo termina em bênção para o povo da aliança.","A fé responde à interpretação hostil da realidade com o caráter e a promessa de Deus."],
 sermon:{idea:"É possível descansar no meio da ameaça quando sabemos que a salvação pertence ao Senhor.",need:"Medimos a presença de Deus pelo número de problemas e facilmente adotamos o diagnóstico dos nossos adversários.",movements:[{title:"Quando todos dizem que Deus nos deixou",vv:"vv. 1–2",point:"A crise externa tenta produzir uma conclusão teológica falsa."},{title:"Quem Deus é muda a noite",vv:"vv. 3–6",point:"Escudo, resposta e sustentação permitem repouso antes da solução."},{title:"A salvação continua pertencendo a Deus",vv:"vv. 7–8",point:"A oração pede intervenção, mas termina confessando a fonte da libertação."}],climax:"‘Eu me deitei e dormi; acordei, porque o Senhor me sustentou’ (v. 5).",gospel:"Jesus, o Filho de Davi rejeitado, entregou-se à morte e foi levantado pelo Pai; nele a igreja aprende que nem rejeição nem morte anulam a promessa de Deus.",applications:["recusar diagnósticos espirituais baseados apenas nas circunstâncias","orar antes de reagir ao medo","buscar descanso na providência sem negar a realidade da ameaça"]}
},
"4":{
 titleVerse:true,
 sources:["Texto Massorético","Calvino, Comentário dos Salmos 1–35","Efésios 4:26 como uso canônico de Sl 4:4","NET Bible Notes"],
 steps:[
 {n:1,label:"Confira o texto que será estudado",technical:"Texto e variantes",body:"A sobrescrição o apresenta como salmo de Davi para instrumentos de cordas. A situação histórica específica não é informada. O v. 4 contém uma forma que pode ser entendida como ‘tremei’ ou ‘irai-vos’; a Septuaginta está por trás do uso em Efésios 4:26. A interpretação deve preservar o sentido do contexto: interromper o pecado, refletir no leito e voltar-se para Deus."},
 {n:2,label:"Ouça o Salmo como poesia hebraica",technical:"Leitura e cantilação",body:"Ouça a passagem da oração para o confronto com os homens, depois para o conselho pastoral e, no final, para o repouso. É um salmo que termina em silêncio e sono depois de uma disputa pública."},
 {n:3,label:"Veja onde cada verso se divide",technical:"Cólons e acentos",body:"O poema se organiza em quatro movimentos: apelo a Deus, fala aos adversários, instrução e confiança final.",items:["v. 1 — pedido de resposta.","vv. 2–3 — confronto com os que desonram e pergunta sobre vaidade.","vv. 4–5 — conselho: parem, reflitam, confiem e adorem corretamente.","vv. 6–8 — pedido pela luz do rosto de Deus e descanso maior que a prosperidade material."]},
 {n:4,label:"Confirme se essas divisões fazem sentido",technical:"Sintaxe e paralelismo",body:"Os pronomes e imperativos confirmam as mudanças de interlocutor. Davi começa falando com Deus, passa a falar aos homens e volta a falar com Deus. O v. 8 fecha com primeira pessoa e um causal: ele dorme seguro porque o Senhor o faz habitar em segurança."},
 {n:5,label:"Observe o ritmo e as mudanças de tamanho",technical:"Escansão",body:"O ritmo é mais variado que no Salmo 1. A principal mudança significativa é a desaceleração no final: perguntas e imperativos cedem lugar a uma declaração de repouso. A forma acompanha a passagem da agitação para a segurança."},
 {n:6,label:"Veja como uma linha responde à outra",technical:"Paralelismo",body:"As linhas frequentemente passam de acusação para correção e de desejo humano para dom divino.",items:["v. 1: experiência passada de alívio sustenta o pedido presente.","vv. 2–3: honra transformada em vergonha // separação que Deus faz para o piedoso.","vv. 4–5: agitação interior // silêncio; sacrifício correto // confiança.","vv. 6–7: pergunta pela prosperidade // resposta na luz do rosto de Deus.","v. 8: deitar em paz // segurança concedida por Deus."]},
 {n:7,label:"Perceba as repetições e imagens importantes",technical:"Recursos poéticos",body:"‘Coração’, ‘rosto’, ‘paz’ e ‘segurança’ organizam o final. A imagem da luz do rosto de Deus vem da linguagem de bênção pactual. O contraste entre abundância de cereal e vinho e alegria dada por Deus corrige uma ideia materialista de bênção."},
 {n:8,label:"Separe os grandes blocos",technical:"Estrofes",body:"A mudança de interlocutor e de função permite quatro blocos.",items:["v. 1 — oração.","vv. 2–3 — confronto.","vv. 4–5 — instrução.","vv. 6–8 — confiança e descanso."]},
 {n:9,label:"Veja o desenho do Salmo inteiro",technical:"Macroestrutura",body:"A arquitetura vai de pressão externa para quietude interior. Davi não resolve a crise vencendo o debate; ele termina deitado diante de Deus. O centro pastoral é deslocar a confiança de sinais externos de prosperidade para a presença favorável de Deus."},
 {n:10,label:"Note o que foge do padrão",technical:"Desvios significativos",body:"O maior contraste é entre a fala pública dos vv. 2–5 e o recolhimento do v. 8. O salmo termina com uma única pessoa dormindo em paz, embora o conflito ainda exista. Essa mudança coincide com a mensagem e merece peso homilético."},
 {n:11,label:"Resuma a mensagem em uma frase",technical:"Proposição",body:"A paz verdadeira nasce quando o coração abandona a vaidade, recebe a luz do rosto de Deus e confia nele mais do que em sinais externos de prosperidade."},
 {n:12,label:"Coloque o Salmo no conjunto da Bíblia",technical:"Situação canônica e cristológica",body:"Efésios 4 usa a linguagem do v. 4 para instruir a igreja sobre ira e pecado, mostrando que o salmo continua formando a vida do povo de Deus. Cristologicamente, não há profecia direta; oramos o salmo em Cristo, por quem a bênção do rosto de Deus nos alcança e em quem a paz com Deus se torna fundamento para uma vida pacificada."}
 ],
 theology:["A presença de Deus é bem maior que prosperidade material.","A graça não elimina o chamado à santidade: o salmo ordena interromper o pecado e confiar.","Paz é fruto da segurança dada por Deus, não de controle das circunstâncias.","A adoração verdadeira e a ética cotidiana permanecem unidas."],
 sermon:{idea:"A luz do rosto de Deus dá uma paz que circunstâncias favoráveis não conseguem produzir.",need:"Tentamos curar ansiedade com aprovação, prosperidade e controle, enquanto o coração continua agitado.",movements:[{title:"Leve a pressão a Deus",vv:"v. 1",point:"A oração começa lembrando a fidelidade já experimentada."},{title:"Pare de alimentar a vaidade",vv:"vv. 2–5",point:"A fé chama o coração ao arrependimento, reflexão e confiança."},{title:"Prefira o rosto de Deus aos sinais de sucesso",vv:"vv. 6–8",point:"A alegria da presença de Deus termina em descanso real."}],climax:"‘Em paz me deito e logo pego no sono’ (v. 8).",gospel:"Em Cristo temos paz com Deus e recebemos a bênção do seu favor; por isso a paz cristã não precisa esperar que todas as disputas terminem.",applications:["examinar o que usamos como prova de que Deus nos ama","resolver ira antes que vire pecado","praticar oração noturna que entregue o controle a Deus"]}
},
"5":{
 titleVerse:true,
 sources:["Texto Massorético","Calvino, Comentário dos Salmos 1–35","Romanos 3:13","NET Bible Notes"],
 steps:[
 {n:1,label:"Confira o texto que será estudado",technical:"Texto e variantes",body:"A sobrescrição associa o salmo ao mestre de canto e contém uma indicação musical difícil de traduzir com certeza. O poema é uma oração matinal de Davi. Não precisamos inventar um instrumento específico para entender a mensagem. O texto contrasta o Deus santo com a fala enganosa dos ímpios e a confiança do adorador."},
 {n:2,label:"Ouça o Salmo como poesia hebraica",technical:"Leitura e cantilação",body:"Ouça a repetição dos pedidos iniciais e a mudança para declarações fortes sobre o caráter de Deus. Depois o salmista volta à primeira pessoa, descreve os inimigos e termina com a alegria dos que se refugiam em Deus."},
 {n:3,label:"Veja onde cada verso se divide",technical:"Cólons e acentos",body:"Cinco movimentos aparecem com clareza.",items:["vv. 1–3 — oração da manhã.","vv. 4–6 — Deus não se agrada do mal.","vv. 7–8 — entrada na casa de Deus e pedido de direção.","vv. 9–10 — diagnóstico da fala inimiga e pedido de juízo.","vv. 11–12 — alegria e proteção dos que se refugiam em Deus."]},
 {n:4,label:"Confirme se essas divisões fazem sentido",technical:"Sintaxe e paralelismo",body:"Os imperativos ‘dá ouvidos’, ‘atende’, ‘escuta’ abrem a oração. A série de negativas em vv. 4–6 define a santidade de Deus. O ‘eu, porém’ do v. 7 marca contraste. No final, os verbos de alegria no plural ampliam a oração de Davi para todos os que amam o nome de Deus."},
 {n:5,label:"Observe o ritmo e as mudanças de tamanho",technical:"Escansão",body:"A escansão mostra variedade normal de um lamento. A mudança mais importante é funcional: oração curta, declaração sobre Deus, pedido de direção, imprecação e doxologia de confiança. O peso deve cair nessas mudanças de função, não em diferenças pequenas de contagem."},
 {n:6,label:"Veja como uma linha responde à outra",technical:"Paralelismo",body:"O poema usa paralelos para intensificar tanto oração quanto denúncia.",items:["vv. 1–3: ouvir palavras → considerar gemido → atender clamor.","vv. 4–6: Deus não tem prazer no mal → o mal não permanece diante dele → praticantes são julgados.","vv. 7–8: misericórdia permite aproximação → justiça de Deus orienta o caminho.","v. 9: boca sem verdade → interior destrutivo → garganta como sepulcro → língua lisonjeira.","vv. 11–12: refúgio → alegria → proteção → favor como escudo."]},
 {n:7,label:"Perceba as repetições e imagens importantes",technical:"Recursos poéticos",body:"Boca, garganta e língua tornam o pecado verbal quase corporal. Paulo usa parte dessa descrição em Romanos 3 para mostrar a corrupção humana de maneira mais ampla. No lado positivo, o favor de Deus envolve o justo como escudo."},
 {n:8,label:"Separe os grandes blocos",technical:"Estrofes",body:"As mudanças de assunto e de pessoa sustentam cinco blocos.",items:["vv. 1–3 — clamor.","vv. 4–6 — santidade e juízo.","vv. 7–8 — culto e direção.","vv. 9–10 — mentira e justiça.","vv. 11–12 — refúgio e bênção."]},
 {n:9,label:"Veja o desenho do Salmo inteiro",technical:"Macroestrutura",body:"O salmo começa com o adorador falando e termina com uma comunidade inteira alegrando-se. Entre esses pontos, a santidade de Deus explica tanto o juízo do mal quanto a possibilidade de aproximação pela misericórdia. Justiça e graça não competem no poema."},
 {n:10,label:"Note o que foge do padrão",technical:"Desvios significativos",body:"A descrição do v. 9 se destaca pela acumulação de imagens do corpo e pela densidade da fala corrupta. Isso prepara o pedido de justiça do v. 10. O final, porém, muda radicalmente o tom: de denúncia para alegria coletiva."},
 {n:11,label:"Resuma a mensagem em uma frase",technical:"Proposição",body:"O Deus santo que rejeita a mentira conduz e protege, por sua misericórdia, aqueles que de manhã procuram sua direção e nele encontram refúgio."},
 {n:12,label:"Coloque o Salmo no conjunto da Bíblia",technical:"Situação canônica e cristológica",body:"Romanos 3 usa a linguagem do v. 9 para mostrar que o problema da fala corrupta não pertence apenas aos inimigos de Davi; ele revela a condição pecaminosa humana. Isso impede uma leitura presunçosa de ‘nós bons contra eles maus’. Em Cristo, pecadores são recebidos pela misericórdia e aprendem a pedir tanto justiça quanto transformação.",items:["A imprecação é apelo ao juiz, não licença para vingança privada.","O evangelho nos inclui primeiro entre os pecadores que precisam de misericórdia.","Santidade de Deus fundamenta tanto juízo quanto direção moral."]}
 ],
 theology:["Deus é santo e não pode ser tratado como neutro diante do mal.","A aproximação do adorador ocorre pela abundância da misericórdia de Deus.","A Palavra corrige nossa fala e nossa visão de justiça.","O juízo pedido no salmo deve ser submetido ao Juiz perfeito, não à vingança pessoal."],
 sermon:{idea:"O mesmo Deus que julga a mentira recebe em misericórdia quem busca sua direção.",need:"É fácil denunciar a mentira dos outros sem perceber que também dependemos da misericórdia do Deus santo.",movements:[{title:"Comece o dia diante do Rei",vv:"vv. 1–3",point:"Oração orienta o coração antes que outras vozes o façam."},{title:"Leve a santidade de Deus a sério",vv:"vv. 4–10",point:"Deus não banaliza o mal, e sua justiça deve moldar nosso pedido de direção."},{title:"Faça de Deus seu refúgio",vv:"vv. 11–12",point:"O favor que não merecemos se torna proteção e alegria."}],climax:"‘Eu, porém, pela riqueza da tua misericórdia, entrarei em tua casa’ (v. 7).",gospel:"Em Cristo, o Deus santo recebe pecadores sem negar sua justiça; a cruz é o lugar em que juízo e misericórdia se encontram.",applications:["começar o dia em oração antes de consumir outras vozes","vigiar a própria fala antes de denunciar a alheia","entregar a justiça final a Deus"]}
},
"6":{
 titleVerse:true,
 sources:["Texto Massorético","Calvino, Comentário dos Salmos 1–35","A Medida do Louvor, gênero do lamento","tradição reformada sobre disciplina e graça"],
 steps:[
 {n:1,label:"Confira o texto que será estudado",technical:"Texto e variantes",body:"O Salmo 6 é um lamento individual e foi tradicionalmente classificado entre os salmos penitenciais. A sobrescrição contém indicação musical difícil. O texto sugere sofrimento físico intenso, mas não nos permite diagnosticar a doença nem afirmar que toda enfermidade é punição direta por pecado específico."},
 {n:2,label:"Ouça o Salmo como poesia hebraica",technical:"Leitura e cantilação",body:"Ouça como as frases iniciais são pedidos curtos sob disciplina, depois se alongam na descrição do choro e, por fim, ficam firmes quando Davi declara que Deus ouviu sua súplica."},
 {n:3,label:"Veja onde cada verso se divide",technical:"Cólons e acentos",body:"Quatro movimentos organizam o salmo.",items:["vv. 1–3 — dor e pedido para que a disciplina não venha em ira.","vv. 4–5 — pedido de livramento apoiado na misericórdia de Deus.","vv. 6–7 — exaustão e lágrimas.","vv. 8–10 — certeza de que Deus ouviu e reversão da situação dos inimigos."]},
 {n:4,label:"Confirme se essas divisões fazem sentido",technical:"Sintaxe e paralelismo",body:"A repetição de imperativos ‘tem misericórdia’, ‘cura’, ‘volta’, ‘livra’ confirma a seção de petição. No final, os verbos passam de pedido para declaração: ‘o Senhor ouviu’. A mudança gramatical marca a mudança espiritual do lamento para confiança."},
 {n:5,label:"Observe o ritmo e as mudanças de tamanho",technical:"Escansão",body:"O ritmo é irregular como convém a um lamento intenso. O dado mais importante é a contração final: depois de longas descrições de lágrimas, a certeza ‘o Senhor ouviu’ produz frases mais decisivas. Não é necessário inventar um ‘metro de tristeza’."},
 {n:6,label:"Veja como uma linha responde à outra",technical:"Paralelismo",body:"Os pares aprofundam a experiência.",items:["vv. 1–2: não me repreendas em ira // tem misericórdia porque estou fraco.","v. 3: corpo perturbado // alma perturbada, ampliando o sofrimento.","vv. 4–5: volta e livra // salva por tua misericórdia.","vv. 6–7: noite de choro // olhos consumidos.","vv. 8–10: Deus ouviu → inimigos perdem sua posição de triunfo."]},
 {n:7,label:"Perceba as repetições e imagens importantes",technical:"Recursos poéticos",body:"Lágrimas, cama, olhos e morte dão corpo à aflição. A linguagem sobre não louvar no Sheol é argumento de quem pede preservação para continuar confessando Deus entre os vivos; não deve ser usada isoladamente para negar a esperança bíblica além da morte."},
 {n:8,label:"Separe os grandes blocos",technical:"Estrofes",body:"A progressão é clara e típica do lamento.",items:["vv. 1–3 — queixa.","vv. 4–5 — petição com apelo à misericórdia.","vv. 6–7 — descrição da aflição.","vv. 8–10 — confiança porque Deus ouviu."]},
 {n:9,label:"Veja o desenho do Salmo inteiro",technical:"Macroestrutura",body:"O salmo vai da disciplina temida para a oração, da oração para lágrimas e das lágrimas para a certeza de audiência divina. A resolução começa quando Davi sabe que foi ouvido, antes de narrar qualquer mudança física concreta."},
 {n:10,label:"Note o que foge do padrão",technical:"Desvios significativos",body:"A virada do v. 8 é abrupta: ‘apartai-vos de mim’ substitui o tom frágil anterior. A razão aparece três vezes em sequência: o Senhor ouviu meu choro, minha súplica e minha oração. Essa repetição sustenta o novo tom de confiança."},
 {n:11,label:"Resuma a mensagem em uma frase",technical:"Proposição",body:"O sofredor pode pedir misericórdia no meio da disciplina porque a fidelidade de Deus é maior que sua fraqueza, e a certeza de ser ouvido transforma lágrimas em confiança antes mesmo da crise desaparecer."},
 {n:12,label:"Coloque o Salmo no conjunto da Bíblia",technical:"Situação canônica e cristológica",body:"Este salmo é oração da igreja em Cristo, não uma profecia direta do Messias. Jesus entrou plenamente na dor humana e levou sobre si a condenação que seu povo merecia. Por isso, a disciplina paternal do crente deve ser distinguida da ira condenatória: em Cristo não há condenação, mas ainda há correção amorosa e formação santa.",items:["Não atribuir toda doença a pecado específico.","Não transformar disciplina em mérito ou pagamento pelo pecado.","Orar com liberdade porque a reconciliação com Deus se apoia em Cristo."]}
 ],
 theology:["A disciplina divina não deve ser confundida com condenação para quem está em Cristo.","A misericórdia de Deus, e não o mérito do sofredor, é a base do pedido.","Lamento bíblico permite linguagem corporal e emocional forte.","Ser ouvido por Deus é uma forma real de graça mesmo antes da mudança das circunstâncias."],
 sermon:{idea:"A misericórdia de Deus permite que o sofredor chore, peça correção sem ira e volte a confiar porque foi ouvido.",need:"Na dor, tendemos a interpretar todo sofrimento como rejeição final ou a esconder a fraqueza para parecer espiritualmente fortes.",movements:[{title:"Peça misericórdia no meio da correção",vv:"vv. 1–5",point:"O salmista não reivindica mérito; apela à compaixão e ao amor de Deus."},{title:"Diga a Deus o peso real da dor",vv:"vv. 6–7",point:"A fé não exige linguagem higienizada sobre sofrimento."},{title:"Descanse no Deus que ouve",vv:"vv. 8–10",point:"A virada começa com audiência divina, não com controle humano."}],climax:"‘O Senhor ouviu a voz do meu lamento’ (v. 8).",gospel:"Cristo suportou a condenação do pecado; por isso quem está nele pode receber disciplina como filho e clamar por misericórdia sem medo de abandono judicial.",applications:["distinguir culpa real de culpa imaginada","levar a dor a Deus em vez de apenas reprimi-la","interpretar correção pela cruz, não pela condenação"]}
},
"7":{
 titleVerse:true,
 sources:["Texto Massorético","Calvino, Comentário dos Salmos 1–35","Romanos 12:19; Atos 17:31 como controle canônico de justiça","NET Bible Notes"],
 steps:[
 {n:1,label:"Confira o texto que será estudado",technical:"Texto e variantes",body:"A sobrescrição chama o poema de shiggaion, termo cujo sentido musical/literário é incerto, e menciona Cuxe, benjamita, personagem não identificável com segurança. Davi protesta inocência em relação a uma acusação concreta. Isso não significa que se considere sem pecado em termos absolutos."},
 {n:2,label:"Ouça o Salmo como poesia hebraica",technical:"Leitura e cantilação",body:"Ouça o movimento de refúgio para autoexame, depois para o tribunal de Deus e finalmente para a certeza de que o mal retorna sobre quem o pratica. O salmo soa como uma causa levada ao Juiz."},
 {n:3,label:"Veja onde cada verso se divide",technical:"Cólons e acentos",body:"A estrutura segue a lógica de uma audiência judicial.",items:["vv. 1–2 — pedido de refúgio contra perseguidores.","vv. 3–5 — juramento de inocência quanto à acusação.","vv. 6–11 — chamado para que o Juiz se levante e examine corações.","vv. 12–16 — o juízo e o efeito de retorno do próprio mal.","v. 17 — louvor ao Deus justo."]},
 {n:4,label:"Confirme se essas divisões fazem sentido",technical:"Sintaxe e paralelismo",body:"A condição ‘se fiz isto’ nos vv. 3–5 é jurídica e específica. Depois os imperativos ‘levanta-te’, ‘desperta’ e ‘julga-me’ mudam o foco para Deus. A partir do v. 12 aparecem descrições gerais do modo como a justiça alcança o perverso."},
 {n:5,label:"Observe o ritmo e as mudanças de tamanho",technical:"Escansão",body:"A variação rítmica acompanha a intensidade do processo: clamor, juramento, convocação do Juiz, sentença e louvor. As linhas que acumulam imagens de armas, cova e violência ficam mais densas, reforçando o perigo e a reversão do mal."},
 {n:6,label:"Veja como uma linha responde à outra",technical:"Paralelismo",body:"O paralelismo trabalha sobretudo com intensificação e causa–efeito.",items:["vv. 1–2: perseguidores → imagem de leão que despedaça.","vv. 3–5: culpa específica → disposição de aceitar a consequência se for verdadeira.","vv. 6–11: Deus se levanta → julga povos → sonda mente e coração.","vv. 12–16: o ímpio prepara violência → cai na própria cova.","v. 17: justiça de Deus → louvor ao seu nome."]},
 {n:7,label:"Perceba as repetições e imagens importantes",technical:"Recursos poéticos",body:"Leão, escudo, arco, flechas, gravidez do mal e cova formam uma rede de imagens judiciais e militares. A imagem da gravidez é forte: o perverso concebe maldade, gera mentira e acaba atingido pelo que produziu."},
 {n:8,label:"Separe os grandes blocos",technical:"Estrofes",body:"A mudança de função é nítida.",items:["vv. 1–2 — refúgio.","vv. 3–5 — autoexame judicial.","vv. 6–11 — apelo ao Juiz justo.","vv. 12–16 — descrição da justiça retributiva.","v. 17 — doxologia."]},
 {n:9,label:"Veja o desenho do Salmo inteiro",technical:"Macroestrutura",body:"O salmista sai da posição de vítima acuada e coloca o caso no tribunal de Deus. O centro teológico é que Deus sonda corações e julga com justiça; o final mostra que a justiça não precisa ser produzida por vingança pessoal do ofendido."},
 {n:10,label:"Note o que foge do padrão",technical:"Desvios significativos",body:"O juramento dos vv. 3–5 é excepcionalmente ousado e deve ser lido como protesto de inocência numa causa específica. O outro destaque é o longo desenvolvimento da ‘reversão’: a violência retorna sobre a cabeça do violento. Esses elementos explicam por que a oração pode terminar em louvor."},
 {n:11,label:"Resuma a mensagem em uma frase",technical:"Proposição",body:"O justo falsamente acusado pode entregar sua causa ao Deus que sonda corações e julga retamente, confiando que o mal não precisa ser vencido por vingança privada porque a própria justiça de Deus o faz retornar sobre o perverso."},
 {n:12,label:"Coloque o Salmo no conjunto da Bíblia",technical:"Situação canônica e cristológica",body:"O Novo Testamento confirma que a vingança final pertence a Deus e que ele julgará o mundo por meio de Cristo. O salmo não autoriza o crente a declarar inocência absoluta; ele permite pedir vindicação em acusações concretas. Jesus é o único verdadeiramente inocente em sentido total e o Juiz designado por Deus.",items:["Distinguir inocência numa questão específica de impecabilidade.","Entregar a vingança a Deus.","Ler o juízo final à luz do Cristo que é Salvador e Juiz."]}
 ],
 theology:["Deus conhece motivos, não apenas aparências.","Justificação pela fé não elimina a possibilidade de integridade real em causas concretas.","A justiça divina liberta o crente da necessidade de vingança pessoal.","Cristo é ao mesmo tempo o inocente sofredor e o Juiz final."],
 sermon:{idea:"Quem é acusado injustamente pode entregar a causa ao Juiz que conhece o coração e não deixa o mal ter a última palavra.",need:"Quando somos feridos, queremos ocupar o lugar do juiz ou então provar uma inocência absoluta que não possuímos.",movements:[{title:"Leve a acusação ao verdadeiro refúgio",vv:"vv. 1–5",point:"Davi se examina e coloca a causa diante de Deus."},{title:"Deixe Deus ocupar o tribunal",vv:"vv. 6–11",point:"O centro da esperança é o caráter do Juiz, não a eloquência do acusado."},{title:"Confie na justiça que desarma a vingança",vv:"vv. 12–17",point:"O mal retorna ao perverso e o salmista termina adorando."}],climax:"‘Deus é justo juiz’ (v. 11).",gospel:"Jesus sofreu a acusação injusta sem tomar vingança e recebeu do Pai toda autoridade para julgar; nele somos absolvidos da culpa real e libertos para entregar a Deus as injustiças sofridas.",applications:["examinar-se honestamente antes de pedir vindicação","não usar linguagem de justiça para alimentar ressentimento","confiar no juízo de Deus quando não conseguimos limpar nosso nome"]}
},
"8":{
 titleVerse:true,
 sources:["A Medida do Louvor, cap. 31","Texto Massorético","Mateus 21:16","Hebreus 2:6–9","1 Coríntios 15:27"],
 steps:[
 {n:1,label:"Confira o texto que será estudado",technical:"Texto e variantes",body:"A sobrescrição contém o termo gittith, provavelmente uma indicação musical cujo sentido exato é incerto. O texto celebra a majestade do nome de Deus e a dignidade humana dada por ele. No trecho sobre crianças há diferença entre a forma hebraica e a redação grega citada em Mateus 21; a citação apostólica deve ser respeitada sem apagar a forma do Texto Massorético."},
 {n:2,label:"Ouça o Salmo como poesia hebraica",technical:"Leitura e cantilação",body:"Ouça a mesma frase sobre a majestade do nome de Deus no começo e no fim. Tudo o que o salmo diz sobre o ser humano fica cercado por adoração. A pergunta ‘que é o homem?’ deve soar dentro dessa moldura."},
 {n:3,label:"Veja onde cada verso se divide",technical:"Cólons e acentos",body:"A estrutura é muito clara: abertura doxológica, glória de Deus e fraqueza humana, pergunta central, resposta sobre dignidade e domínio, e repetição da abertura.",items:["v. 1 — refrão de abertura.","v. 2 — glória de Deus manifestada por meio dos pequenos contra inimigos.","vv. 3–4 — contemplação do céu e pergunta sobre o homem.","vv. 5–8 — dignidade e vocação humana sobre a criação.","v. 9 — refrão final."]},
 {n:4,label:"Confirme se essas divisões fazem sentido",technical:"Sintaxe e paralelismo",body:"A pergunta central usa dois termos paralelos para a fragilidade humana e dois verbos que descrevem a atenção de Deus. A resposta muda de pergunta para afirmação: Deus fez, coroou e colocou sob os pés. O sujeito decisivo é Deus; a dignidade humana é recebida."},
 {n:5,label:"Observe o ritmo e as mudanças de tamanho",technical:"Escansão",body:"A pergunta central é formalmente equilibrada, reforçando sua força contemplativa. A enumeração dos animais depois se expande, mostrando a extensão do domínio delegado. O salmo abre e fecha com a mesma frase, o que é mais importante que qualquer contagem isolada."},
 {n:6,label:"Veja como uma linha responde à outra",technical:"Paralelismo",body:"O paralelismo passa do cosmos ao homem e do homem à vocação.",items:["v. 1: nome de Deus na terra // glória sobre os céus.","v. 2: fraqueza das crianças // silenciamento de inimigos.","vv. 3–4: grandeza dos céus // pequenez humana.","vv. 5–6: pouco menor que seres celestiais // coroado e colocado sobre obras de Deus.","vv. 7–8: animais domésticos → selvagens → aves → peixes; o domínio é descrito por enumeração crescente."]},
 {n:7,label:"Perceba as repetições e imagens importantes",technical:"Recursos poéticos",body:"A inclusão literal do primeiro e do último verso enquadra toda antropologia em doxologia. ‘Obra dos teus dedos’ diminui o cosmos diante de Deus, enquanto ‘coroa’ e ‘sob os pés’ descrevem a vocação real do ser humano. O contraste criança/inimigo também mostra a preferência divina por instrumentos fracos."},
 {n:8,label:"Separe os grandes blocos",technical:"Estrofes",body:"Quatro blocos aparecem por inclusão, mudança temática e pergunta-resposta.",items:["vv. 1–2 — majestade de Deus e força manifestada na fraqueza.","vv. 3–4 — criação e pergunta sobre o homem.","vv. 5–8 — resposta: dignidade e domínio delegado.","v. 9 — doxologia final."]},
 {n:9,label:"Veja o desenho do Salmo inteiro",technical:"Macroestrutura",body:"A grande moldura é ‘majestoso é o teu nome’. Dentro dela, a pergunta sobre o valor humano encontra resposta não na autonomia, mas na decisão de Deus de lembrar, visitar, coroar e confiar responsabilidade ao homem."},
 {n:10,label:"Note o que foge do padrão",technical:"Desvios significativos",body:"O contraste mais surpreendente é entre a grandeza cósmica e a fragilidade dos instrumentos escolhidos por Deus: crianças e seres humanos frágeis. A pergunta central interrompe a descrição da criação e obriga o leitor a interpretar a humanidade a partir do Criador."},
 {n:11,label:"Resuma a mensagem em uma frase",technical:"Proposição",body:"A dignidade humana não nasce do tamanho ou da autonomia do homem, mas do Deus majestoso que se lembra dele, o coroa e lhe confia uma vocação real dentro da criação."},
 {n:12,label:"Coloque o Salmo no conjunto da Bíblia",technical:"Situação canônica e cristológica",body:"Hebreus 2 lê os vv. 4–6 à luz de Jesus: a vocação humana de Gênesis ainda não aparece plenamente realizada em nós, mas já a vemos cumprida no Filho do Homem coroado depois do sofrimento. Cristo é o verdadeiro e último Adão. Isso preserva o sentido criacional e mostra seu cumprimento, sem transformar cada animal em símbolo.",items:["Mateus 21 aplica a linguagem das crianças ao louvor recebido por Jesus.","Hebreus 2 faz de Cristo o cumprimento da vocação humana.","1 Coríntios 15 usa a linguagem de ‘todas as coisas debaixo dos pés’ na vitória final de Cristo."]}
 ],
 theology:["A antropologia bíblica começa com a majestade de Deus, não com autoestima autônoma.","A dignidade humana é criação e vocação recebida.","A queda tornou incompleta nossa experiência de domínio; Cristo, segundo Adão, a cumpre.","O poder de Deus pode ser exibido por instrumentos socialmente fracos."],
 sermon:{idea:"Só entendemos o valor do ser humano quando o vemos dentro da majestade de Deus e do domínio cumprido por Cristo.",need:"Oscilamos entre exaltar o homem como centro do universo e tratá-lo como acidente sem valor.",movements:[{title:"A grandeza pertence primeiro a Deus",vv:"vv. 1–2",point:"A moldura do salmo impede que a dignidade humana vire idolatria."},{title:"A pergunta que o céu provoca",vv:"vv. 3–4",point:"A imensidão da criação torna surpreendente a atenção de Deus ao homem."},{title:"A vocação recebida e cumprida em Cristo",vv:"vv. 5–9",point:"Deus coroa o homem e o Filho do Homem realiza plenamente essa vocação."}],climax:"‘Que é o homem, que dele te lembres?’ (v. 4).",gospel:"Jesus entrou em nossa humanidade, foi humilhado e agora está coroado de glória; nele a vocação humana é restaurada e encaminhada à consumação.",applications:["tratar todo ser humano com dignidade dada por Deus","exercer domínio como mordomia e não exploração","encontrar identidade final no segundo Adão"]}
},
"9":{
 titleVerse:true,
 sources:["Texto Massorético","Calvino, Comentário dos Salmos 1–35","A Medida do Louvor, índice formal do acróstico","comparação canônica com Salmo 10"],
 steps:[
 {n:1,label:"Confira o texto que será estudado",technical:"Texto e variantes",body:"A sobrescrição contém expressão musical de sentido incerto. Salmos 9 e 10 formam um par importante: juntos apresentam traços de um acróstico alfabético e, em algumas tradições antigas, são tratados como uma unidade. Isso explica irregularidades que parecem estranhas quando o Salmo 9 é lido isoladamente."},
 {n:2,label:"Ouça o Salmo como poesia hebraica",technical:"Leitura e cantilação",body:"Ouça a alternância entre louvor pelo juízo já realizado e novos pedidos para que Deus se levante. O poema não é simples celebração de vitória; ele mantém a tensão entre atos de justiça lembrados e justiça ainda esperada."},
 {n:3,label:"Veja onde cada verso se divide",technical:"Cólons e acentos",body:"O salmo pode ser lido em cinco movimentos.",items:["vv. 1–2 — louvor pessoal.","vv. 3–6 — derrota dos inimigos e memória do juízo.","vv. 7–10 — reinado justo de Deus e refúgio dos oprimidos.","vv. 11–14 — chamado ao louvor e nova súplica.","vv. 15–20 — nações presas pelo próprio mal e pedido final de juízo."]},
 {n:4,label:"Confirme se essas divisões fazem sentido",technical:"Sintaxe e paralelismo",body:"Os tempos verbais alternam atos celebrados como realizados e pedidos ainda abertos. A linguagem do trono em vv. 7–8 explica a confiança do salmista. No final, os imperativos ‘levanta-te’ e ‘põe medo’ mostram que a memória do passado alimenta a oração presente."},
 {n:5,label:"Observe o ritmo e as mudanças de tamanho",technical:"Escansão",body:"O acróstico e as pausas de Selâ influenciam o desenho mais que uma métrica uniforme. O padrão alfabético é incompleto se olharmos só o Salmo 9; a continuidade com o 10 torna a irregularidade mais compreensível. O ritmo deve ser lido junto ao par, não como prova independente de autoria ou data."},
 {n:6,label:"Veja como uma linha responde à outra",technical:"Paralelismo",body:"Os pares reforçam o governo judicial de Deus.",items:["vv. 1–2: agradecer → narrar maravilhas → alegrar-se → cantar.","vv. 3–6: inimigos recuam → Deus sustenta a causa → memória deles é apagada.","vv. 7–10: trono permanente → juízo reto → refúgio para o oprimido.","vv. 11–14: cantar entre o povo → lembrar que Deus ouve o aflito → pedir graça.","vv. 15–18: nações caem na própria cova → necessitado não é esquecido para sempre.","vv. 19–20: Deus se levanta → homem aprende que é mortal."]},
 {n:7,label:"Perceba as repetições e imagens importantes",technical:"Recursos poéticos",body:"Trono, cova, rede, portas da morte e portas de Sião formam contrastes fortes. O salmista quer sair das portas da morte para anunciar louvor nas portas de Sião. O acróstico liga formalmente o poema ao Salmo 10."},
 {n:8,label:"Separe os grandes blocos",technical:"Estrofes",body:"A alternância entre louvor e petição permite cinco blocos.",items:["vv. 1–2 — louvor.","vv. 3–6 — juízo lembrado.","vv. 7–10 — caráter do Rei-Juiz.","vv. 11–14 — missão de louvar e pedido pessoal.","vv. 15–20 — justiça sobre as nações e oração final."]},
 {n:9,label:"Veja o desenho do Salmo inteiro",technical:"Macroestrutura",body:"O passado e o futuro são unidos pelo trono permanente de Deus. O salmista olha para vitórias já dadas e pede novo juízo porque o caráter do Rei não mudou. A conexão acróstica com o Salmo 10 continua a pergunta sobre a aparente prosperidade do ímpio."},
 {n:10,label:"Note o que foge do padrão",technical:"Desvios significativos",body:"A maior irregularidade é o acróstico incompleto, que ganha sentido quando lido com o Salmo 10. Outro destaque é a oscilação entre ‘já julgaste’ e ‘levanta-te’. Ela impede uma teologia triunfalista: a justiça de Deus é real, mas ainda esperamos sua manifestação completa."},
 {n:11,label:"Resuma a mensagem em uma frase",technical:"Proposição",body:"O Deus que já julgou com justiça permanece entronizado como refúgio dos oprimidos, por isso seu povo pode lembrar livramentos passados, clamar por justiça presente e confiar que o necessitado não será esquecido para sempre."},
 {n:12,label:"Coloque o Salmo no conjunto da Bíblia",technical:"Situação canônica e cristológica",body:"Salmos 9–10 devem ser lidos juntos. A esperança no Rei que julga as nações encontra sua consumação no reino de Cristo, a quem o Pai confiou o juízo. Não devemos transformar as nações inimigas do salmo em povos modernos escolhidos por preferência política; a linha canônica culmina no juízo universal e justo do Messias."}
 ],
 theology:["O trono de Deus é a estabilidade por trás de uma história instável.","A justiça divina inclui atenção especial ao oprimido e ao necessitado.","Memória dos atos de Deus alimenta oração, não triunfalismo.","O juízo universal pertence ao Messias e não pode ser apropriado por agendas nacionais."],
 sermon:{idea:"Porque Deus continua no trono, a memória de sua justiça passada sustenta a esperança do oprimido no presente.",need:"Quando a injustiça demora, confundimos demora com esquecimento e podemos procurar salvadores políticos absolutos.",movements:[{title:"Lembre o que Deus já fez",vv:"vv. 1–6",point:"Louvor recorda atos concretos de justiça."},{title:"Olhe para o trono que permanece",vv:"vv. 7–14",point:"O caráter do Rei é a ponte entre passado e presente."},{title:"Ore porque o necessitado não é esquecido",vv:"vv. 15–20",point:"A justiça ainda esperada continua sendo objeto legítimo de oração."}],climax:"‘O Senhor permanece no seu trono para sempre’ (v. 7).",gospel:"O Pai entregou o juízo ao Filho; o mesmo Cristo que acolhe pecadores arrependidos julgará com perfeita justiça e fará cessar a opressão.",applications:["lembrar livramentos sem negar sofrimentos presentes","interceder por vítimas de opressão","recusar idolatria de poder político"]}
},
"10":{
 titleVerse:false,
 sources:["Texto Massorético","Calvino, Comentário dos Salmos 1–35","A Medida do Louvor, Salmos 9–10 como par acróstico","Romanos 3 como contexto canônico da corrupção humana"],
 steps:[
 {n:1,label:"Confira o texto que será estudado",technical:"Texto e variantes",body:"O Salmo 10 não tem sobrescrição e continua o desenho alfabético iniciado no Salmo 9. A pergunta inicial ‘por que te conservas longe?’ deve ser lida como linguagem de lamento, não como doutrina de que Deus realmente abandonou seu governo. O próprio final responde à percepção inicial: o Senhor é Rei para sempre."},
 {n:2,label:"Ouça o Salmo como poesia hebraica",technical:"Leitura e cantilação",body:"Ouça a longa descrição do perverso no centro. O leitor quase fica preso à voz e ao comportamento dele. Então os imperativos ‘levanta-te’ e ‘não te esqueças’ quebram essa ocupação e recolocam Deus no centro."},
 {n:3,label:"Veja onde cada verso se divide",technical:"Cólons e acentos",body:"Quatro movimentos cobrem todo o poema.",items:["v. 1 — pergunta sobre a aparente distância de Deus.","vv. 2–11 — retrato detalhado do ímpio e de sua violência contra o fraco.","vv. 12–15 — pedido para Deus se levantar e quebrar o poder do perverso.","vv. 16–18 — confissão do reinado de Deus e certeza de que ele ouve o humilde."]},
 {n:4,label:"Confirme se essas divisões fazem sentido",technical:"Sintaxe e paralelismo",body:"A seção central muda para terceira pessoa e inclui falas interiores do ímpio: ele diz a si mesmo que Deus não vê, não cobrará e não há risco. Os imperativos do v. 12 mudam a direção. No final, os verbos passam para confissão: Deus ouviu, fortalece e faz justiça."},
 {n:5,label:"Observe o ritmo e as mudanças de tamanho",technical:"Escansão",body:"A seção sobre o perverso é longa e pesada, fazendo o leitor sentir o domínio aparente do mal. O fecho é mais compacto e seguro. A mudança formal combina com a mensagem: o mal parece ocupar muito espaço, mas não recebe a última palavra."},
 {n:6,label:"Veja como uma linha responde à outra",technical:"Paralelismo",body:"O retrato do ímpio é cumulativo.",items:["vv. 2–4: orgulho → perseguição → ausência prática de Deus em seus pensamentos.","vv. 5–7: sensação de estabilidade → desprezo do juízo → fala cheia de fraude e opressão.","vv. 8–11: emboscada → captura do fraco → falsa conclusão de que Deus esqueceu.","vv. 12–15: levanta-te → vê a aflição → cobra o mal → quebra o braço do perverso.","vv. 16–18: Deus é Rei → ouve o humilde → faz justiça ao órfão e oprimido."]},
 {n:7,label:"Perceba as repetições e imagens importantes",technical:"Recursos poéticos",body:"O ímpio aparece como predador escondido: leão, emboscada, rede. Suas frases internas revelam ‘ateísmo prático’: não é apenas negar Deus com a boca, mas viver como se ele não visse nem julgasse. A mão de Deus e o braço do perverso aparecem em contraste de poder."},
 {n:8,label:"Separe os grandes blocos",technical:"Estrofes",body:"A estrutura acompanha a pergunta, o diagnóstico, a oração e a resposta de fé.",items:["v. 1 — problema percebido.","vv. 2–11 — poder aparente do ímpio.","vv. 12–15 — petição por intervenção.","vv. 16–18 — resposta teológica: o Senhor reina e ouve."]},
 {n:9,label:"Veja o desenho do Salmo inteiro",technical:"Macroestrutura",body:"O salmo começa perguntando onde Deus está e termina afirmando quem Deus é. O centro descreve a narrativa que o perverso conta a si mesmo: ‘Deus não vê’. O final a destrói: Deus ouve, fortalece e julga."},
 {n:10,label:"Note o que foge do padrão",technical:"Desvios significativos",body:"O peso desproporcional da descrição do perverso é intencional: a experiência do oprimido realmente é dominada por ele. A virada ocorre quando o salmista para de narrar o ímpio e ordena sua oração diretamente a Deus. O final curto funciona como veredito contra uma longa propaganda do mal."},
 {n:11,label:"Resuma a mensagem em uma frase",technical:"Proposição",body:"Mesmo quando a violência faz Deus parecer distante e o perverso vive como se nunca fosse prestar contas, o Senhor continua Rei, vê a aflição, ouve o humilde e fará justiça ao vulnerável."},
 {n:12,label:"Coloque o Salmo no conjunto da Bíblia",technical:"Situação canônica e cristológica",body:"Lido com o Salmo 9, o poema completa um quadro de justiça e espera. O Novo Testamento amplia o diagnóstico do pecado para toda a humanidade e anuncia que Deus julgará por meio de Cristo. A igreja ora este salmo como povo unido ao Rei justo e como comunidade chamada a cuidar do órfão e do oprimido, não apenas a esperar passivamente pelo juízo.",items:["Não identificar o ‘ímpio’ apenas com nossos adversários ideológicos.","Reconhecer o ateísmo prático que também ameaça o coração religioso.","Unir oração por justiça a prática concreta de justiça e misericórdia."]}
 ],
 theology:["Deus pode parecer distante sem ter abandonado o trono.","O pecado inclui uma teologia prática: viver como se Deus não visse.","O cuidado de Deus com o vulnerável é parte de sua justiça régia.","A esperança reformada no juízo futuro produz perseverança e responsabilidade presente."],
 sermon:{idea:"O mal pode parecer dominante, mas não consegue transformar o Rei em ausente nem o oprimido em esquecido.",need:"A longa duração da injustiça nos tenta a crer na mesma mentira do perverso: Deus não vê e não cobrará.",movements:[{title:"Diga a Deus quando ele parece longe",vv:"v. 1",point:"O lamento bíblico permite a pergunta sem abandonar a fé."},{title:"Enxergue a teologia escondida no mal",vv:"vv. 2–11",point:"O perverso age a partir da crença prática de que nunca prestará contas."},{title:"Ore e viva à luz do Rei que vê",vv:"vv. 12–18",point:"A oração termina em certeza de justiça e atenção ao vulnerável."}],climax:"‘O Senhor é Rei eterno’ (v. 16).",gospel:"Jesus é o Rei a quem todo juízo foi confiado e que, em sua própria humilhação, se identificou com os fracos; nele há perdão para pecadores e certeza de justiça final.",applications:["levar a sensação de abandono a Deus em vez de abandoná-lo","examinar onde vivemos como se Deus não visse","defender o vulnerável como expressão de fidelidade ao Rei"]}
}
});
