window.MANUAL_ANALYSES=window.MANUAL_ANALYSES||{};
Object.assign(window.MANUAL_ANALYSES,{
"11":{
 titleVerse:true,
 sources:["Texto Massorético","Calvino, Comentário dos Salmos 1–35","A Medida do Louvor, gênero de confiança","NET Bible Notes"],
 steps:[
 {n:1,label:"Confira o texto que será estudado",technical:"Texto e variantes",body:"A sobrescrição identifica o poema como de Davi. Não há situação histórica definida. O v. 1 contém a fala de conselheiros ou adversários que recomendam fugir ‘como pássaro para o monte’. O salmista não rejeita toda fuga prudente; ele rejeita tratar a fuga como sua esperança final, porque já declarou que seu refúgio está no Senhor."},
 {n:2,label:"Ouça o Salmo como poesia hebraica",technical:"Leitura e cantilação",body:"Ouça primeiro a voz do medo nos vv. 1–3 e depois a resposta segura dos vv. 4–7. O poema é breve e trabalha com uma oposição espacial: fundamentos abalados na terra e trono firme no céu."},
 {n:3,label:"Veja onde cada verso se divide",technical:"Cólons e acentos",body:"Duas grandes partes dominam o salmo.",items:["vv. 1–3 — conselho para fugir e descrição da crise.","vv. 4–7 — resposta de fé baseada no trono, no olhar e na justiça de Deus."]},
 {n:4,label:"Confirme se essas divisões fazem sentido",technical:"Sintaxe e paralelismo",body:"A pergunta ‘como dizeis à minha alma?’ introduz uma fala citada. Depois o v. 4 muda completamente o sujeito: ‘O Senhor está no seu santo templo; nos céus tem o seu trono’. A partir daí, os verbos descrevem o que Deus vê, prova, odeia e fará."},
 {n:5,label:"Observe o ritmo e as mudanças de tamanho",technical:"Escansão",body:"O poema é compacto. A tensão se concentra nos vv. 2–3, onde as ameaças são acumuladas. A resposta do v. 4 é curta e firme, produzindo uma sensação de estabilidade. O efeito vem do contraste, não de um metro uniforme."},
 {n:6,label:"Veja como uma linha responde à outra",technical:"Paralelismo",body:"As linhas opõem o que parece acontecer embaixo ao que permanece verdadeiro em cima.",items:["vv. 1–2: fuga sugerida → inimigos já armados.","v. 3: fundamentos destruídos → pergunta sobre o justo.","v. 4: templo santo → trono nos céus → olhos que examinam.","vv. 5–6: Deus prova o justo // odeia o violento // prepara juízo.","v. 7: Deus é justo → ama justiça → os retos verão seu rosto."]},
 {n:7,label:"Perceba as repetições e imagens importantes",technical:"Recursos poéticos",body:"Pássaro, arco, fundamentos, trono, olhos e rosto criam uma sequência de imagens. A crise parece estrutural: ‘fundamentos’ desabam. A resposta não é negar o colapso, mas lembrar que o trono de Deus não está sobre esses fundamentos humanos."},
 {n:8,label:"Separe os grandes blocos",technical:"Estrofes",body:"A mudança de voz e de perspectiva sustenta uma divisão simples.",items:["vv. 1–3 — a leitura do medo.","vv. 4–7 — a leitura da fé a partir do trono de Deus."]},
 {n:9,label:"Veja o desenho do Salmo inteiro",technical:"Macroestrutura",body:"A pergunta ‘o que pode fazer o justo?’ recebe resposta indireta: ele pode continuar refugiado no Deus cujo trono permanece. O salmo desloca o centro do mundo dos fundamentos sociais para o governo celestial de Deus."},
 {n:10,label:"Note o que foge do padrão",technical:"Desvios significativos",body:"O v. 4 é a virada decisiva porque abandona de uma vez a linguagem de colapso e fala do trono. O último verso também se destaca ao terminar não com fuga, mas com visão: ‘os retos lhe contemplarão a face’. A direção final é presença, não escapismo."},
 {n:11,label:"Resuma a mensagem em uma frase",technical:"Proposição",body:"Quando os fundamentos humanos parecem ruir, o justo não precisa fazer do medo seu refúgio, porque o Senhor continua no trono, vê com perfeita justiça e conduz os retos à sua presença."},
 {n:12,label:"Coloque o Salmo no conjunto da Bíblia",technical:"Situação canônica e cristológica",body:"Este é principalmente um salmo que a igreja ora em Cristo. O Novo Testamento confirma que o governo e o juízo foram confiados ao Filho e que a esperança do povo de Deus termina em vê-lo. Não devemos converter o texto em promessa de estabilidade política; sua estabilidade é o trono de Deus.",items:["Fuga pode ser prudente; o erro é torná-la salvador final.","A justiça de Deus inclui exame do justo e juízo do violento.","Em Cristo, a esperança de contemplar a face de Deus ganha sua forma plena."]}
 ],
 theology:["O trono de Deus não depende da estabilidade das instituições humanas.","Providência inclui exame e formação do justo.","Violência é moralmente odiosa a Deus, mesmo quando parece eficiente.","A esperança final do justo é comunhão com Deus, não apenas sobrevivência."],
 sermon:{idea:"Quando os fundamentos cedem, nossa segurança continua sendo o trono que não cede.",need:"Confundimos estabilidade social, financeira ou institucional com a própria estabilidade de Deus.",movements:[{title:"Escute a voz do medo sem torná-la senhor",vv:"vv. 1–3",point:"A ameaça pode ser real, mas sua interpretação pode ser idólatra."},{title:"Olhe acima dos fundamentos",vv:"vv. 4–6",point:"O trono e o olhar de Deus redefinem a crise."},{title:"Deseje a face, não apenas a fuga",vv:"v. 7",point:"A esperança termina em presença e justiça."}],climax:"‘O Senhor está no seu santo templo; nos céus tem o Senhor seu trono’ (v. 4).",gospel:"Em Cristo, o Rei entronizado, nossa reconciliação com Deus e nosso destino de vê-lo são seguros mesmo quando estruturas terrenas falham.",applications:["separar prudência de pânico","avaliar decisões pela justiça de Deus e não só pela sobrevivência","cultivar esperança escatológica em vez de nostalgia institucional"]}
},
"12":{
 titleVerse:true,
 sources:["Texto Massorético","Calvino, Comentário dos Salmos 1–35","A Medida do Louvor, lamento comunitário","NET Bible Notes"],
 steps:[
 {n:1,label:"Confira o texto que será estudado",technical:"Texto e variantes",body:"A sobrescrição contém a indicação sheminith, provavelmente musical e de sentido incerto. O v. 7 tem uma dificuldade pronominal: a tradição de tradução varia entre Deus guardar ‘essas palavras’, ‘os pobres’ ou ‘nos’. A segurança do salmo, porém, não depende dessa escolha isolada: o contraste central é entre palavras humanas enganosas e palavras divinas puras."},
 {n:2,label:"Ouça o Salmo como poesia hebraica",technical:"Leitura e cantilação",body:"Ouça a quantidade de linguagem sobre boca, lábios e palavras nos vv. 1–4. Depois, no v. 5, o próprio Deus fala. O poema muda de uma sociedade barulhenta e falsa para uma palavra divina limpa e confiável."},
 {n:3,label:"Veja onde cada verso se divide",technical:"Cólons e acentos",body:"Quatro movimentos organizam o lamento.",items:["vv. 1–2 — desaparecimento da fidelidade e domínio da fala falsa.","vv. 3–4 — pedido para Deus cortar a arrogância dos lábios.","v. 5 — palavra-oráculo de Deus em favor do pobre.","vv. 6–8 — pureza da palavra divina e persistência de uma geração corrupta."]},
 {n:4,label:"Confirme se essas divisões fazem sentido",technical:"Sintaxe e paralelismo",body:"Os vv. 1–4 são dominados por terceira pessoa e pedido de juízo. O v. 5 muda para primeira pessoa divina: ‘agora me levantarei’. Essa mudança de falante é a fronteira mais forte do poema. Depois o salmista comenta a qualidade das palavras que acabou de ouvir."},
 {n:5,label:"Observe o ritmo e as mudanças de tamanho",technical:"Escansão",body:"A forma não é completamente regular. O contraste mais significativo é de voz e densidade: muitas palavras humanas falsas são respondidas por uma palavra divina curta e decisiva. A imagem da prata refinada sete vezes intensifica a ideia de pureza, mas não autoriza numerologia."},
 {n:6,label:"Veja como uma linha responde à outra",technical:"Paralelismo",body:"O paralelismo mostra a corrupção da comunicação e a confiabilidade de Deus.",items:["vv. 1–2: fiéis desaparecem → cada um mente ao próximo.","vv. 3–4: lábios bajuladores → língua arrogante → pretensão de autonomia.","v. 5: opressão dos pobres → Deus se levanta → promete segurança.","v. 6: palavras do Senhor → prata refinada; pureza moral explicada por imagem de metal.","vv. 7–8: guarda divina → perversos continuam circulando; preservação não significa ausência imediata do mal."]},
 {n:7,label:"Perceba as repetições e imagens importantes",technical:"Recursos poéticos",body:"Lábios, língua, palavras e fala dominam o poema. A prata refinada funciona como resposta concreta à duplicidade dos ‘lábios lisonjeiros’. A oposição é verbal e moral: o que humanos dizem pode manipular; o que Deus diz é confiável."},
 {n:8,label:"Separe os grandes blocos",technical:"Estrofes",body:"As mudanças de voz e assunto permitem quatro blocos.",items:["vv. 1–2 — diagnóstico social.","vv. 3–4 — pedido de juízo sobre a arrogância verbal.","v. 5 — resposta de Deus.","vv. 6–8 — confiança na Palavra em meio a uma sociedade ainda corrompida."]},
 {n:9,label:"Veja o desenho do Salmo inteiro",technical:"Macroestrutura",body:"A macroestrutura é fala humana corrompida → palavra divina → comentário sobre a palavra divina. O salmo não termina afirmando que os perversos desapareceram; termina com o crente segurando a Palavra enquanto eles ainda circulam."},
 {n:10,label:"Note o que foge do padrão",technical:"Desvios significativos",body:"O oráculo do v. 5 interrompe o lamento e deve receber destaque. A segunda tensão importante é o final: a promessa de proteção não produz uma cena idealizada; os perversos continuam por toda parte. A Palavra dá segurança sem falsificar a realidade."},
 {n:11,label:"Resuma a mensagem em uma frase",technical:"Proposição",body:"Quando a fala pública é dominada por mentira, bajulação e arrogância, o povo de Deus encontra segurança na palavra pura do Senhor, que vê a opressão e se levanta em favor do vulnerável."},
 {n:12,label:"Coloque o Salmo no conjunto da Bíblia",technical:"Situação canônica e cristológica",body:"A Escritura inteira mantém o contraste entre a mentira humana e a verdade de Deus. Cristo é a Palavra fiel e aquele em cuja boca não houve engano. A aplicação reformada não é apenas defender uma doutrina abstrata da Bíblia, mas viver como comunidade cuja fala é moldada pelo Deus verdadeiro e cuja confiança permanece quando o ambiente social continua corrompido."}
 ],
 theology:["A veracidade de Deus fundamenta a confiança na Escritura.","Pureza da Palavra não significa simplicidade superficial; significa ausência de engano.","Deus se identifica judicialmente com a causa do pobre oprimido.","Preservação divina pode coexistir com uma sociedade ainda dominada pelo pecado."],
 sermon:{idea:"Em um mundo de palavras manipuladoras, a palavra de Deus continua pura e capaz de sustentar os oprimidos.",need:"Somos vulneráveis tanto à mentira dos outros quanto ao desejo de controlar pessoas com nossa própria fala.",movements:[{title:"Reconheça a crise da palavra humana",vv:"vv. 1–4",point:"A corrupção social passa pela boca e pela pretensão de autonomia."},{title:"Ouça quando Deus entra na conversa",vv:"v. 5",point:"A palavra divina responde à opressão real."},{title:"Apoie-se no que é puro",vv:"vv. 6–8",point:"A segurança vem da fidelidade de Deus, mesmo antes da sociedade mudar."}],climax:"‘Agora me levantarei, diz o Senhor’ (v. 5).",gospel:"Jesus é a testemunha fiel e o Salvador sem engano; nele a Palavra de Deus não apenas denuncia nossa fala, mas cria um povo de verdade.",applications:["examinar bajulação e manipulação na própria fala","dar peso à Palavra acima do ruído social","usar linguagem verdadeira em defesa dos vulneráveis"]}
},
"13":{
 titleVerse:true,
 sources:["A Medida do Louvor, cap. 26","Texto Massorético","Calvino, Comentário dos Salmos 1–35","Mateus 27; Marcos 15 como horizonte do lamento"],
 steps:[
 {n:1,label:"Confira o texto que será estudado",technical:"Texto e variantes",body:"A sobrescrição é simples: salmo de Davi para o mestre de canto. No v. 2 há uma variante antiga que acrescenta ‘e de noite’ à frase sobre a dor no coração; o Texto Massorético tem apenas ‘de dia’. Não devemos escolher a leitura mais longa só porque ela produziria um efeito rítmico interessante. A análise segue o Texto Massorético.",items:["A numeração desta página segue a ARA: vv. 1–6.","O livro anexado usa numeração hebraica, na qual a sobrescrição desloca os números em um verso."]},
 {n:2,label:"Ouça o Salmo como poesia hebraica",technical:"Leitura e cantilação",body:"Ouça quatro vezes ‘até quando?’ nos dois primeiros versículos. Depois o tom muda para imperativos: ‘atenta’, ‘responde’, ‘ilumina’. O último verso muda novamente e se expande em confiança, alegria e canto."},
 {n:3,label:"Veja onde cada verso se divide",technical:"Cólons e acentos",body:"O salmo é um modelo claro de lamento em três partes.",items:["vv. 1–2 — queixa: quatro perguntas ‘até quando?’.","vv. 3–4 — petição: olhar, resposta e vida diante do perigo da morte e do inimigo.","vv. 5–6 — confiança e voto de louvor: fidelidade, salvação e canto."]},
 {n:4,label:"Confirme se essas divisões fazem sentido",technical:"Sintaxe e paralelismo",body:"A gramática reforça a mudança. A primeira parte é interrogativa; a segunda usa imperativos; a terceira começa com ‘eu, porém’ e um verbo de confiança no perfeito, indicando confiança já assumida. Depois vêm formas que projetam alegria e canto."},
 {n:5,label:"Observe o ritmo e as mudanças de tamanho",technical:"Escansão",body:"O padrão dominante é aproximadamente 4+3, e não o suposto 3+2 que às vezes é chamado de ‘metro do lamento’. A linha mais longa é a que descreve ruminação interior no v. 2; a forma se alonga justamente onde a mente parece não conseguir encerrar a angústia. O v. 6 termina em três partes e expande o poema para o louvor.",items:["A forma modula o lamento; não há metro obrigatório para tristeza.","O comprimento do v. 2 coincide com um ponto semanticamente carregado, por isso o desvio é relevante."]},
 {n:6,label:"Veja como uma linha responde à outra",technical:"Paralelismo",body:"A queixa desce por círculos e a confiança sobe para Deus.",items:["v. 1: Deus parece esquecer → Deus parece esconder o rosto.","v. 2: conflito dentro da alma → inimigo se levanta fora dela.","v. 3: olha e responde → ilumina os olhos; audiência divina → preservação da vida.","v. 4: triunfo do inimigo → alegria dos adversários se Davi cair.","vv. 5–6: fidelidade de Deus → confiança → alegria na salvação → canto pelo bem recebido."]},
 {n:7,label:"Perceba as repetições e imagens importantes",technical:"Recursos poéticos",body:"A anáfora ‘até quando?’ estrutura a queixa. ‘Esconder o rosto’ usa linguagem relacional da aliança. A palavra hesed no v. 5 fala de amor leal e compromisso de Deus, não de otimismo genérico. A passagem de ‘meu coração’ angustiado para ‘meu coração’ alegre fecha uma transformação interna."},
 {n:8,label:"Separe os grandes blocos",technical:"Estrofes",body:"Três blocos, definidos por função, gramática e tom.",items:["vv. 1–2 — queixa.","vv. 3–4 — pedido.","vv. 5–6 — confiança e louvor."]},
 {n:9,label:"Veja o desenho do Salmo inteiro",technical:"Macroestrutura",body:"O poema não resolve a crise narrando uma mudança externa. A grande virada é ‘eu, porém’ no v. 5. O inimigo continua existindo, mas o lugar de fala mudou: da sensação de ausência para a fidelidade pactual de Deus."},
 {n:10,label:"Note o que foge do padrão",technical:"Desvios significativos",body:"A longa linha da ruminação e o tricolo final são os desvios mais claros. Um encena o peso da angústia; o outro dá espaço à confiança, alegria e canto. Forma e sentido convergem, por isso ambos devem influenciar a exposição."},
 {n:11,label:"Resuma a mensagem em uma frase",technical:"Proposição",body:"O crente pode dizer a Deus sem disfarce que se sente esquecido e, ainda antes de a situação mudar, voltar a cantar porque sua confiança repousa no amor fiel da aliança e não na leitura imediata das circunstâncias."},
 {n:12,label:"Coloque o Salmo no conjunto da Bíblia",technical:"Situação canônica e cristológica",body:"O lamento encontra seu horizonte máximo em Cristo, que tomou nos lábios o Salmo 22 na cruz. Não precisamos afirmar que cada frase do Salmo 13 é previsão direta de Jesus. A igreja ora este salmo em Cristo: o Filho realmente entrou na experiência de abandono judicial para que os que estão nele nunca sejam abandonados de forma condenatória.",items:["Lamento é exercício da fé, não sua negação.","A base da virada é hesed, fidelidade pactual.","A cruz impede tanto desespero absoluto quanto triunfalismo apressado."]}
 ],
 theology:["A aliança dá linguagem para protestar diante de Deus sem romper com Deus.","Fé pode existir antes da resolução emocional completa.","Hesed é fidelidade comprometida, fundamento mais sólido que circunstâncias.","A cruz dá ao lamento cristão um horizonte que não depende de negar a dor."],
 sermon:{idea:"A fé bíblica pode perguntar ‘até quando?’ e ainda assim terminar cantando porque se apoia na fidelidade de Deus.",need:"Ou fingimos que a dor não existe, ou interpretamos a demora de Deus como abandono definitivo.",movements:[{title:"Diga a Deus a sensação de ausência",vv:"vv. 1–2",point:"O lamento dá forma fiel à dor real."},{title:"Transforme a queixa em pedido",vv:"vv. 3–4",point:"A fé continua falando com o Deus que parece silencioso."},{title:"Apoie-se na fidelidade antes da mudança",vv:"vv. 5–6",point:"A virada nasce do caráter de Deus, não de novas circunstâncias."}],climax:"‘Eu, porém, confio na tua graça’ (v. 5).",gospel:"Cristo atravessou o abandono da cruz e foi vindicado na ressurreição; unidos a ele, podemos lamentar sem concluir que a aliança acabou.",applications:["usar os salmos para dar linguagem à dor","converter ruminação em petição concreta","lembrar promessas antes de avaliar a presença de Deus pelas emoções"]}
},
"14":{
 titleVerse:true,
 sources:["Texto Massorético","Calvino, Comentário dos Salmos 1–35","Romanos 3:10–12","Salmo 53 como paralelo canônico"],
 steps:[
 {n:1,label:"Confira o texto que será estudado",technical:"Texto e variantes",body:"A sobrescrição o apresenta como salmo de Davi. O Salmo 53 é um paralelo muito próximo, com diferenças que mostram transmissão e reutilização do mesmo poema. A frase ‘não há Deus’ descreve o pensamento moral do insensato: ele vive como se Deus não existisse ou não importasse, e o resultado aparece em suas obras."},
 {n:2,label:"Ouça o Salmo como poesia hebraica",technical:"Leitura e cantilação",body:"Ouça a repetição de ‘não há quem’ e a ampliação da corrupção. Depois surge uma pergunta dirigida aos que devoram o povo e, no fim, um desejo concentrado: que a salvação venha de Sião."},
 {n:3,label:"Veja onde cada verso se divide",technical:"Cólons e acentos",body:"Três movimentos resumem o poema.",items:["vv. 1–3 — corrupção universal observada por Deus.","vv. 4–6 — confrontação dos malfeitores e proteção do pobre.","v. 7 — esperança de salvação vindo de Sião e restauração do povo."]},
 {n:4,label:"Confirme se essas divisões fazem sentido",technical:"Sintaxe e paralelismo",body:"As negativas acumuladas nos vv. 1–3 dão universalidade ao diagnóstico. O v. 4 muda para pergunta judicial. O v. 7 muda novamente para desejo e esperança comunitária. A progressão é diagnóstico → juízo → restauração."},
 {n:5,label:"Observe o ritmo e as mudanças de tamanho",technical:"Escansão",body:"A seção inicial é repetitiva e deliberadamente pesada, como um laudo moral. O fechamento é mais curto e esperançoso. A mudança mais significativa é temática e verbal, não um padrão métrico rígido."},
 {n:6,label:"Veja como uma linha responde à outra",technical:"Paralelismo",body:"O paralelismo intensifica o diagnóstico e depois abre espaço para esperança.",items:["v. 1: negar Deus na prática → corromper-se → praticar abominação.","vv. 2–3: Deus procura alguém que entenda e busque → todos se desviam → ninguém faz o bem.","vv. 4–6: devorar o povo → não invocar Deus → medo repentino porque Deus está com o justo.","v. 7: salvação de Sião → restauração do povo → alegria de Jacó e Israel."]},
 {n:7,label:"Perceba as repetições e imagens importantes",technical:"Recursos poéticos",body:"A repetição de negativas remove qualquer base para autoexaltação. A imagem de ‘comer meu povo como pão’ descreve exploração desumanizadora. O final usa Sião como lugar da esperança pactual, não como poder mágico do território."},
 {n:8,label:"Separe os grandes blocos",technical:"Estrofes",body:"A mudança de função produz três blocos.",items:["vv. 1–3 — pecado universal.","vv. 4–6 — juízo e presença de Deus com o justo aflito.","v. 7 — esperança de salvação e restauração."]},
 {n:9,label:"Veja o desenho do Salmo inteiro",technical:"Macroestrutura",body:"O poema desce até ‘ninguém faz o bem’ e então sobe para uma esperança que não pode vir da capacidade humana descrita anteriormente. A salvação precisa vir de Deus, de Sião, porque o diagnóstico não deixa espaço para autorredenção."},
 {n:10,label:"Note o que foge do padrão",technical:"Desvios significativos",body:"O v. 7 rompe a sequência de negativas e introduz desejo de salvação. Essa ruptura é teologicamente importante: a esperança não nasce de uma melhora gradual da humanidade, mas de intervenção divina."},
 {n:11,label:"Resuma a mensagem em uma frase",technical:"Proposição",body:"A humanidade que vive como se Deus não importasse torna-se incapaz de produzir a justiça de que precisa, de modo que sua esperança só pode estar na salvação que Deus traz ao seu povo."},
 {n:12,label:"Coloque o Salmo no conjunto da Bíblia",technical:"Situação canônica e cristológica",body:"Paulo usa o diagnóstico dos vv. 1–3 em Romanos 3 dentro de sua demonstração de que judeus e gentios estão debaixo do pecado. Essa interpretação apostólica impede que usemos o salmo apenas para apontar ‘os ateus’. A salvação esperada de Sião encontra seu cumprimento no Messias que justifica pecadores incapazes de produzir sua própria justiça.",items:["O problema é universal, inclusive religioso.","A graça não é complemento de pessoas quase boas; é resgate de quem não pode se justificar.","A santificação posterior nunca deve ser confundida com a base da justificação."]}
 ],
 theology:["Depravação total não significa que todos sejam tão maus quanto poderiam, mas que o pecado alcança todas as dimensões humanas.","A justificação precisa vir de fora do pecador.","Deus permanece com a geração dos justos por sua graça pactual.","A esperança de Sião chega ao seu cumprimento no Messias."],
 sermon:{idea:"Quando a Bíblia diz que ninguém faz o bem, ela fecha a porta da autojustificação e abre a necessidade da salvação de Deus.",need:"Preferimos localizar a corrupção em grupos de que não gostamos e preservar uma versão aceitável de nós mesmos.",movements:[{title:"O problema é mais profundo que ateísmo intelectual",vv:"vv. 1–3",point:"Viver sem referência a Deus corrompe entendimento e prática."},{title:"A injustiça produz vítimas reais",vv:"vv. 4–6",point:"O pecado universal não é abstrato; ele devora pessoas."},{title:"A salvação precisa vir de Deus",vv:"v. 7",point:"A única esperança compatível com o diagnóstico é intervenção divina."}],climax:"‘Não há quem faça o bem, não há nem um sequer’ (v. 3).",gospel:"Romanos 3 leva esse diagnóstico diretamente à justiça de Deus oferecida em Cristo a pecadores que não podem produzi-la.",applications:["abandonar superioridade moral","reconhecer efeitos sociais do pecado","descansar na justiça recebida pela fé e produzir justiça como fruto"]}
},
"15":{
 titleVerse:true,
 sources:["Texto Massorético","Calvino, Comentário dos Salmos 1–35","A Medida do Louvor, exercício sugerido e estrutura de estrofe","Hebreus como horizonte de acesso a Deus"],
 steps:[
 {n:1,label:"Confira o texto que será estudado",technical:"Texto e variantes",body:"A sobrescrição o chama ‘Salmo de Davi’. O poema usa linguagem de entrada no santuário: quem pode hospedar-se na tenda e morar no monte santo? A resposta descreve caráter e relações. O texto não ensina que obras compram entrada diante de Deus; ele descreve a vida coerente com quem pertence à aliança."},
 {n:2,label:"Ouça o Salmo como poesia hebraica",technical:"Leitura e cantilação",body:"Ouça uma pergunta dupla no v. 1 e uma longa resposta em forma de retrato moral. O final ‘jamais será abalado’ funciona como conclusão e promessa de estabilidade."},
 {n:3,label:"Veja onde cada verso se divide",technical:"Cólons e acentos",body:"O salmo tem pergunta, resposta e conclusão.",items:["v. 1 — quem pode permanecer diante de Deus?","vv. 2–5a — retrato do adorador íntegro em ações, fala, relacionamentos e uso do dinheiro.","v. 5b — conclusão: quem vive assim não será abalado."]},
 {n:4,label:"Confirme se essas divisões fazem sentido",technical:"Sintaxe e paralelismo",body:"A pergunta usa duas imagens de permanência. A resposta alterna particípios e formas negativas: faz o bem / não difama / honra / não muda sua palavra / não explora. Isso cria um retrato de integridade positiva e negativa, pública e privada."},
 {n:5,label:"Observe o ritmo e as mudanças de tamanho",technical:"Escansão",body:"O ritmo é listatório e acumulativo. A estabilidade do final contrasta com a sequência de provas éticas anteriores. O poema não precisa de simetria perfeita para funcionar; a força está no inventário concreto de uma vida inteira diante de Deus."},
 {n:6,label:"Veja como uma linha responde à outra",technical:"Paralelismo",body:"As linhas ampliam o conceito de integridade.",items:["v. 2: andar com integridade → praticar justiça → falar verdade no coração.","v. 3: não difamar → não fazer mal → não lançar afronta.","v. 4: rejeitar o desprezível → honrar quem teme o Senhor → manter palavra mesmo com prejuízo.","v. 5: não explorar com juros → não aceitar suborno → estabilidade final."]},
 {n:7,label:"Perceba as repetições e imagens importantes",technical:"Recursos poéticos",body:"Tenda, monte e ‘não ser abalado’ ligam ética a presença de Deus. Boca, coração, próximo, dinheiro e juramento mostram que santidade não é ritual isolado. A lista funciona como merismo prático: toda a vida pertence ao culto."},
 {n:8,label:"Separe os grandes blocos",technical:"Estrofes",body:"A estrutura é simples e forte.",items:["v. 1 — pergunta de entrada.","vv. 2–5a — caráter de quem vive diante de Deus.","v. 5b — segurança resultante."]},
 {n:9,label:"Veja o desenho do Salmo inteiro",technical:"Macroestrutura",body:"A pergunta é litúrgica, mas a resposta é ética. O salmo impede separar culto de caráter. A estabilidade final não é promessa de uma vida sem dificuldade; é linguagem de permanência diante de Deus e de integridade pactual."},
 {n:10,label:"Note o que foge do padrão",technical:"Desvios significativos",body:"O elemento mais chamativo é que a resposta à pergunta sobre acesso ao santuário não lista ritos, mas relações e justiça cotidiana. Essa escolha estrutural é a principal ênfase do salmo."},
 {n:11,label:"Resuma a mensagem em uma frase",technical:"Proposição",body:"Quem vive na presença do Deus santo demonstra essa comunhão por integridade concreta no coração, na fala, nos relacionamentos e no uso do poder e do dinheiro."},
 {n:12,label:"Coloque o Salmo no conjunto da Bíblia",technical:"Situação canônica e cristológica",body:"A leitura reformada mantém lei e evangelho em ordem. O salmo descreve a santidade requerida de quem habita com Deus, mas ninguém a cumpre de modo perfeito. Cristo é o adorador perfeitamente justo e o mediador que nos dá acesso; unidos a ele, somos justificados e então chamados a uma obediência sincera, ainda imperfeita, como fruto da graça.",items:["Não pregar ‘cumpra a lista e Deus aceitará você’.","Não esvaziar a lista porque somos justificados pela fé.","Justificação fundamenta, e não elimina, a santificação."]}
 ],
 theology:["Santidade toca ética, dinheiro, fala e relações.","A justificação é pela graça, mas a fé verdadeira não permanece estéril.","Cristo cumpre a justiça perfeita que nós não conseguimos oferecer.","A igreja deve tratar integridade como parte da adoração."],
 sermon:{idea:"A presença de Deus não combina com uma vida dividida: graça recebida produz integridade concreta.",need:"Queremos separar culto de caráter e, ao mesmo tempo, usar obras como prova de que merecemos estar diante de Deus.",movements:[{title:"A pergunta que expõe nossa necessidade",vv:"v. 1",point:"Quem pode realmente permanecer diante do Santo?"},{title:"A vida que combina com a presença",vv:"vv. 2–5a",point:"Santidade aparece no coração, na boca, no próximo e no dinheiro."},{title:"A estabilidade que não compramos",vv:"v. 5b",point:"A promessa pertence a quem vive pela graça diante de Deus."}],climax:"A resposta ética à pergunta litúrgica: a vida inteira se torna culto.",gospel:"Cristo é o único homem integralmente justo que entrou na presença de Deus por seu próprio mérito; nele recebemos acesso e somos transformados para viver a justiça do salmo.",applications:["alinhar fala pública e coração privado","cumprir promessas mesmo quando custam","rejeitar exploração financeira e favoritismo"]}
},
"16":{
 titleVerse:true,
 sources:["Texto Massorético","Calvino, Comentário dos Salmos 1–35","Atos 2:25–31; 13:35–37","A Medida do Louvor, hermenêutica cristológica reformada"],
 steps:[
 {n:1,label:"Confira o texto que será estudado",technical:"Texto e variantes",body:"A sobrescrição chama o poema de miktam de Davi; o sentido exato de miktam é incerto. Há dificuldades de tradução especialmente nos vv. 2–4, mas a linha central é clara: o Senhor é o bem, a porção e a herança de Davi, em contraste com outros deuses. O v. 10 é decisivo porque o Novo Testamento o interpreta explicitamente."},
 {n:2,label:"Ouça o Salmo como poesia hebraica",technical:"Leitura e cantilação",body:"Ouça a passagem de pedido de proteção para confissão de lealdade, depois para linguagem de herança e conselho e, finalmente, para alegria, segurança e ‘caminho da vida’. O movimento é do refúgio presente à esperança que supera a morte."},
 {n:3,label:"Veja onde cada verso se divide",technical:"Cólons e acentos",body:"Cinco movimentos organizam o salmo.",items:["vv. 1–2 — refúgio e confissão de que o Senhor é o bem supremo.","vv. 3–4 — distinção entre o povo santo e os que correm atrás de outros deuses.","vv. 5–6 — Senhor como porção e herança agradável.","vv. 7–8 — conselho, presença e estabilidade.","vv. 9–11 — alegria, esperança diante do Sheol e caminho da vida."]},
 {n:4,label:"Confirme se essas divisões fazem sentido",technical:"Sintaxe e paralelismo",body:"As possessões ‘minha porção’, ‘meu cálice’, ‘minha herança’ constroem identidade pactual. O ‘tenho o Senhor sempre à minha presença’ funciona como razão para não ser abalado. Os vv. 9–11 acumulam consequências: coração alegre, corpo seguro, não abandono ao Sheol e plenitude de alegria diante de Deus."},
 {n:5,label:"Observe o ritmo e as mudanças de tamanho",technical:"Escansão",body:"O ritmo cresce no final com uma cadeia de motivos de esperança. A mudança mais importante é semântica: linguagem de posse material é transformada em relação — o próprio Senhor é a herança. O fecho se abre para vida, presença e alegria duradoura."},
 {n:6,label:"Veja como uma linha responde à outra",technical:"Paralelismo",body:"As linhas desenvolvem uma teologia da satisfação em Deus.",items:["vv. 1–2: proteção → Senhor como bem.","vv. 3–4: prazer nos santos → recusa dos que multiplicam deuses e dores.","vv. 5–6: porção e cálice → limites agradáveis → bela herança.","vv. 7–8: Deus aconselha → Davi o mantém diante de si → estabilidade.","vv. 9–11: alegria presente → segurança corporal → não corrupção → caminho da vida → plenitude na presença."]},
 {n:7,label:"Perceba as repetições e imagens importantes",technical:"Recursos poéticos",body:"Porção, cálice, linhas de herança e mão direita misturam linguagem levítica, territorial e relacional. O salmista transforma posse em comunhão: Deus não é apenas quem dá a herança, é a própria herança. O final trabalha com caminho, presença e mão direita."},
 {n:8,label:"Separe os grandes blocos",technical:"Estrofes",body:"As mudanças de assunto sustentam cinco blocos.",items:["vv. 1–2 — Deus como bem.","vv. 3–4 — lealdades concorrentes.","vv. 5–6 — herança.","vv. 7–8 — orientação e presença.","vv. 9–11 — vida e esperança além da morte."]},
 {n:9,label:"Veja o desenho do Salmo inteiro",technical:"Macroestrutura",body:"O salmo começa pedindo proteção e termina descrevendo vida diante do rosto de Deus. O eixo é a troca de ‘bens’ por ‘o Senhor como meu bem e porção’. A esperança da vida futura nasce da comunhão presente."},
 {n:10,label:"Note o que foge do padrão",technical:"Desvios significativos",body:"O v. 10 ultrapassa a experiência normal de Davi ao falar de não ser abandonado no Sheol nem ver corrupção de modo que o Novo Testamento considera não plenamente realizável nele. Essa tensão interna é exatamente o tipo de dado que a hermenêutica reformada usa para seguir o texto até Cristo."},
 {n:11,label:"Resuma a mensagem em uma frase",technical:"Proposição",body:"Quem tem o Senhor como seu bem, porção e presença encontra estabilidade que alcança corpo, morte e futuro, porque a comunhão com Deus aponta para o caminho da vida e alegria plena diante dele."},
 {n:12,label:"Coloque o Salmo no conjunto da Bíblia",technical:"Situação canônica e cristológica",body:"Atos 2 e 13 dizem explicitamente que o v. 10 alcança seu cumprimento em Jesus ressuscitado: Davi morreu e viu corrupção; Cristo não foi abandonado à corrupção. Esta é uma leitura cristológica controlada pelo próprio Novo Testamento. O crente recebe a esperança do salmo porque está unido ao Ressuscitado.",items:["Primeiro reconhecer a confiança real de Davi.","Depois observar a promessa que excede Davi.","Por fim seguir a interpretação apostólica até a ressurreição de Cristo."]}
 ],
 theology:["Deus é o bem supremo, não apenas o distribuidor de bens.","Idolatria multiplica dores porque desloca a esperança do único bem suficiente.","A esperança bíblica inclui o corpo e a vitória sobre a corrupção.","A ressurreição de Cristo é fundamento objetivo da esperança do crente."],
 sermon:{idea:"Quando o próprio Deus é nossa porção, nem a morte consegue transformar nossa herança em perda final.",need:"Procuramos segurança no que Deus dá mais do que no próprio Deus e descobrimos que toda posse criada pode ser perdida.",movements:[{title:"Faça de Deus seu bem",vv:"vv. 1–4",point:"Refúgio verdadeiro exige lealdade exclusiva."},{title:"Receba Deus como sua herança",vv:"vv. 5–8",point:"A presença do Senhor redefine a ideia de prosperidade."},{title:"Olhe para a vida que venceu a corrupção",vv:"vv. 9–11",point:"A esperança de Davi se cumpre na ressurreição do Messias."}],climax:"‘Não permitirás que o teu Santo veja corrupção’ (v. 10).",gospel:"Pedro e Paulo aplicam o texto diretamente a Jesus ressuscitado; unidos a ele, temos uma herança que a morte não pode consumir.",applications:["identificar substitutos funcionais de Deus","avaliar bens pela comunhão que promovem ou substituem","enfrentar a morte com esperança ancorada na ressurreição"]}
},
"17":{
 titleVerse:true,
 sources:["Texto Massorético","Calvino, Comentário dos Salmos 1–35","NET Bible Notes","A Medida do Louvor, distinção entre integridade pactual e mérito"],
 steps:[
 {n:1,label:"Confira o texto que será estudado",technical:"Texto e variantes",body:"A sobrescrição chama o texto ‘oração de Davi’. Ele pede que Deus examine lábios, coração e passos e declara inocência em relação à causa apresentada. Isso é linguagem de vindicação em uma disputa, não declaração de impecabilidade absoluta. O v. 15 permite mais de uma leitura de ‘acordar’, mas claramente termina na satisfação de contemplar a presença de Deus."},
 {n:2,label:"Ouça o Salmo como poesia hebraica",technical:"Leitura e cantilação",body:"Ouça a frequência dos pedidos ‘ouve’, ‘atende’, ‘guarda’, ‘livra’. Depois perceba o contraste entre a satisfação dos homens com bens desta vida e a satisfação final do salmista com a face de Deus."},
 {n:3,label:"Veja onde cada verso se divide",technical:"Cólons e acentos",body:"Quatro movimentos cobrem a oração.",items:["vv. 1–5 — pedido de exame e afirmação de integridade na causa.","vv. 6–9 — pedido de resposta e proteção.","vv. 10–14 — descrição dos inimigos e pedido de livramento.","v. 15 — contraste final: ver a face de Deus e ser satisfeito."]},
 {n:4,label:"Confirme se essas divisões fazem sentido",technical:"Sintaxe e paralelismo",body:"O início contém linguagem forense: causa justa, exame, prova. Os vv. 6–9 passam para imperativos de proteção. Os vv. 10–14 descrevem os inimigos e o destino dos que têm sua porção nesta vida. O ‘eu, porém’ final marca contraste forte."},
 {n:5,label:"Observe o ritmo e as mudanças de tamanho",technical:"Escansão",body:"A oração é variada e densa. A lista de ameaças alonga o centro, enquanto o v. 15 fecha com uma declaração concentrada de esperança. A diferença entre muitos inimigos e uma única satisfação final é formalmente eficaz."},
 {n:6,label:"Veja como uma linha responde à outra",technical:"Paralelismo",body:"O paralelismo amplia tanto autoexame quanto proteção.",items:["vv. 1–3: ouvir a causa → provar coração → examinar palavras.","vv. 4–5: evitar caminhos violentos → firmar passos.","vv. 6–9: mostrar amor → guardar como menina dos olhos → esconder sob asas.","vv. 10–12: coração fechado → boca arrogante → cerco → imagem de leão.","vv. 13–15: livra-me dos homens cuja porção é esta vida → eu me satisfarei com tua face."]},
 {n:7,label:"Perceba as repetições e imagens importantes",technical:"Recursos poéticos",body:"Menina dos olhos e sombra das asas são imagens de cuidado. Leão representa a ameaça. ‘Porção nesta vida’ contrasta com ‘ver tua face’. O salmo cria duas formas de satisfação: bens temporais ou presença de Deus."},
 {n:8,label:"Separe os grandes blocos",technical:"Estrofes",body:"Quatro blocos se distinguem por função e interlocução.",items:["vv. 1–5 — exame.","vv. 6–9 — proteção.","vv. 10–14 — inimigos e livramento.","v. 15 — esperança final."]},
 {n:9,label:"Veja o desenho do Salmo inteiro",technical:"Macroestrutura",body:"A oração começa pedindo que Deus veja Davi e termina com Davi esperando ver Deus. Esse movimento ‘Deus me examina → eu verei sua face’ dá unidade ao poema e desloca a vindicação de autopromoção para comunhão."},
 {n:10,label:"Note o que foge do padrão",technical:"Desvios significativos",body:"O último verso se destaca por abandonar completamente os inimigos. Depois de tanta linguagem de perigo, Davi termina falando apenas de Deus. Essa concentração final mostra que a vindicação desejada não é mera derrota do outro, mas presença divina."},
 {n:11,label:"Resuma a mensagem em uma frase",technical:"Proposição",body:"Quem entrega sua causa ao Deus que examina o coração pode pedir proteção contra injustiça e aprender a desejar, acima da vitória sobre inimigos e dos bens desta vida, a satisfação de contemplar a face de Deus."},
 {n:12,label:"Coloque o Salmo no conjunto da Bíblia",technical:"Situação canônica e cristológica",body:"Cristo é o único sofredor cuja inocência é absoluta. O crente ora o Salmo 17 nele, sem fingir impecabilidade, podendo ainda assim pedir vindicação em causas concretas. A esperança de ver Deus encontra sua segurança na obra do Mediador, por quem pecadores justificados terão comunhão plena com o Deus santo."}
 ],
 theology:["Deus conhece coração, fala e comportamento.","Integridade relativa é compatível com confissão de pecado; não é base de justificação.","Proteção e presença são bens maiores que vingança.","A visão final de Deus é esperança escatológica do povo reconciliado."],
 sermon:{idea:"A melhor vindicação não é ver o inimigo cair, mas ser guardado por Deus e terminar satisfeito com sua presença.",need:"Quando somos injustiçados, nossa visão pode ficar tão ocupada com o adversário que esquecemos o bem maior: Deus.",movements:[{title:"Aceite ser examinado pelo Juiz",vv:"vv. 1–5",point:"Vindicação começa com honestidade diante de Deus."},{title:"Peça proteção sem tomar o tribunal",vv:"vv. 6–14",point:"O salmista clama e deixa a justiça nas mãos divinas."},{title:"Deseje o bem maior",vv:"v. 15",point:"A face de Deus é satisfação superior à vitória circunstancial."}],climax:"‘Eu, porém, na justiça contemplarei a tua face’ (v. 15).",gospel:"O inocente Cristo sofreu injustamente para que culpados fossem justificados e recebessem o direito de contemplar Deus em paz.",applications:["submeter nossa narrativa de inocência ao exame de Deus","pedir proteção sem alimentar vingança","ordenar desejos para que presença de Deus seja o bem final"]}
},
"18":{
 titleVerse:true,
 sources:["Texto Massorético","2 Samuel 22","Calvino, Comentário dos Salmos 1–35","Romanos 15:9","aliança davídica de 2 Samuel 7"],
 steps:[
 {n:1,label:"Confira o texto que será estudado",technical:"Texto e variantes",body:"A longa sobrescrição relaciona o salmo às libertações de Davi de seus inimigos e de Saul. O poema aparece também em 2 Samuel 22, com diferenças de transmissão que devem ser comparadas numa análise crítica completa. Essas diferenças não apagam a estrutura central: livramento do rei, justiça pactual, vitória concedida por Deus e promessa à descendência de Davi."},
 {n:2,label:"Ouça o Salmo como poesia hebraica",technical:"Leitura e cantilação",body:"Por ser longo, ouça em blocos. Perceba como o salmista começa com títulos de refúgio, narra uma teofania de enorme escala, volta à história pessoal, descreve a vitória e termina em doxologia e aliança. O tamanho do salmo serve à grandeza do livramento."},
 {n:3,label:"Veja onde cada verso se divide",technical:"Cólons e acentos",body:"A macrodivisão é mais útil que tentar memorizar cada linha isolada.",items:["vv. 1–3 — amor e títulos de refúgio.","vv. 4–6 — ameaça da morte e clamor.","vv. 7–15 — teofania: Deus vem em tempestade e poder.","vv. 16–19 — resgate das águas e dos inimigos.","vv. 20–27 — vindicação e princípio de correspondência moral.","vv. 28–36 — Deus ilumina, treina e sustenta o rei.","vv. 37–45 — vitória e submissão dos inimigos.","vv. 46–50 — louvor, domínio e fidelidade a Davi e sua descendência."]},
 {n:4,label:"Confirme se essas divisões fazem sentido",technical:"Sintaxe e paralelismo",body:"Os verbos mudam de clamor para ação divina, depois para avaliação da conduta de Davi e finalmente para testemunho público. O ‘porque’ e outras partículas causais ligam libertação e caráter de Deus. As declarações de justiça de Davi precisam ser lidas no contexto de fidelidade à sua vocação e causa, não como mérito sem pecado."},
 {n:5,label:"Observe o ritmo e as mudanças de tamanho",technical:"Escansão",body:"A longa teofania expande drasticamente o poema; a forma faz o socorro de Deus parecer cósmico. Mais tarde, a linguagem militar ganha velocidade por verbos sucessivos. O fechamento desacelera em confissão e aliança. Em um salmo tão longo, padrões locais importam mais que uma média única."},
 {n:6,label:"Veja como uma linha responde à outra",technical:"Paralelismo",body:"O paralelismo cria movimento narrativo.",items:["vv. 1–3: rocha → fortaleza → libertador → escudo → torre; títulos se acumulam.","vv. 4–6: morte cerca → clamor sobe ao templo.","vv. 7–15: terra treme → céus descem → trovão e flechas; a vinda de Deus é intensificada.","vv. 16–19: Deus alcança do alto → tira das águas → livra do inimigo forte.","vv. 20–27: fidelidade na causa → resposta justa de Deus; não é esquema de salvação por obras.","vv. 28–45: Deus equipa → Davi avança → inimigos cedem.","vv. 46–50: Deus vive → rei exalta → nações ouvem → amor pactual chega à descendência."]},
 {n:7,label:"Perceba as repetições e imagens importantes",technical:"Recursos poéticos",body:"Rocha, fortaleza, águas, tempestade, escudo, arco, caminho e luz formam uma teologia da providência em imagens. A teofania usa linguagem cósmica para mostrar que o Deus da criação intervém na história do rei. O final amarra o poema à aliança davídica."},
 {n:8,label:"Separe os grandes blocos",technical:"Estrofes",body:"O comprimento exige blocos maiores, cada qual com função própria.",items:["vv. 1–6 — refúgio e clamor.","vv. 7–19 — descida de Deus e resgate.","vv. 20–27 — vindicação pactual.","vv. 28–36 — capacitação divina.","vv. 37–45 — vitória do rei.","vv. 46–50 — louvor e horizonte davídico."]},
 {n:9,label:"Veja o desenho do Salmo inteiro",technical:"Macroestrutura",body:"O salmo transforma uma história pessoal de livramento em teologia régia. O Deus que desce para resgatar Davi é o mesmo que mantém sua aliança e estende a promessa à descendência. Assim, a narrativa aponta além de uma vitória militar isolada."},
 {n:10,label:"Note o que foge do padrão",technical:"Desvios significativos",body:"A teofania é desproporcionalmente grande e isso é significativo: o livramento do rei é interpretado como ação do Senhor da criação. O final também amplia o foco de Davi para ‘sua descendência para sempre’, abrindo o horizonte messiânico."},
 {n:11,label:"Resuma a mensagem em uma frase",technical:"Proposição",body:"O Deus da criação ouve o rei da aliança, desce para libertá-lo, capacita-o para sua vocação e transforma o livramento histórico de Davi em testemunho de fidelidade que alcança sua descendência."},
 {n:12,label:"Coloque o Salmo no conjunto da Bíblia",technical:"Situação canônica e cristológica",body:"O salmo deve ser lido com 2 Samuel 22 e 2 Samuel 7. Romanos 15:9 usa o louvor entre as nações para a expansão da misericórdia de Deus aos gentios. O final sobre Davi e sua descendência encontra seu cumprimento no Filho de Davi. Não aplicamos as guerras de Davi diretamente a conflitos da igreja; a vitória messiânica se cumpre no reino de Cristo.",items:["A justiça de Davi é fidelidade pactual relativa, não impecabilidade meritória.","O rei histórico é tipo real, não alegoria inventada.","Cristo é a descendência davídica em quem a promessa alcança as nações."]}
 ],
 theology:["Providência pode ser celebrada em linguagem cósmica porque o Deus que salva é o Criador.","Obediência pactual é fruto e evidência da graça, não preço da eleição.","A aliança davídica organiza o horizonte messiânico do salmo.","A vitória do Messias alcança as nações sem autorizar militarização da missão da igreja."],
 sermon:{idea:"O Deus que desce para resgatar o rei mantém sua aliança até o Filho de Davi e faz sua misericórdia chegar às nações.",need:"Tendemos a atribuir livramentos à nossa força e a ler vitórias pessoais como se fossem o centro do plano de Deus.",movements:[{title:"Clame ao Deus que é refúgio",vv:"vv. 1–19",point:"A libertação começa em Deus e é narrada como sua intervenção soberana."},{title:"Receba força para uma vocação, não para autonomia",vv:"vv. 20–45",point:"Deus equipa o rei e julga sua causa dentro da aliança."},{title:"Veja a história abrir-se para a promessa",vv:"vv. 46–50",point:"O livramento de Davi termina apontando para a descendência e as nações."}],climax:"A passagem de livramento pessoal para ‘Davi e sua descendência para sempre’ (v. 50).",gospel:"Jesus é o Filho de Davi em quem a fidelidade prometida se torna reino universal e misericórdia para os gentios.",applications:["atribuir livramentos à providência de Deus","usar dons para vocação e serviço, não autoexaltação","ler nossas histórias dentro da história maior do reino de Cristo"]}
},
"19":{
 titleVerse:true,
 sources:["A Medida do Louvor, cap. 31","Texto Massorético","Calvino, Comentário dos Salmos 1–35","Romanos 10:18","Confissão de Fé de Westminster I.1"],
 steps:[
 {n:1,label:"Confira o texto que será estudado",technical:"Texto e variantes",body:"A sobrescrição identifica um salmo de Davi. O poema combina duas formas de revelação: criação e instrução de Deus. O texto hebraico usa El no painel da criação e YHWH repetidamente no painel da Palavra, diferença teologicamente significativa. Não há variante principal que destrua a estrutura em dois painéis e resposta final."},
 {n:2,label:"Ouça o Salmo como poesia hebraica",technical:"Leitura e cantilação",body:"Ouça a liberdade do primeiro painel, com céu, dia, noite e sol, e depois a regularidade quase catequética das seis frases sobre a instrução do Senhor. Por fim, o poema muda do mundo e da Palavra para o próprio coração do salmista."},
 {n:3,label:"Veja onde cada verso se divide",technical:"Cólons e acentos",body:"Três grandes partes são claras.",items:["vv. 1–6 — os céus proclamam a glória de Deus; o sol percorre seu caminho.","vv. 7–10 — seis descrições paralelas da instrução de YHWH e seus efeitos.","vv. 11–14 — o servo responde: advertência, pecados ocultos, preservação e oração final."]},
 {n:4,label:"Confirme se essas divisões fazem sentido",technical:"Sintaxe e paralelismo",body:"O painel da criação usa sintaxe variada e imagens em movimento. O painel da Palavra usa uma fórmula regular: termo da instrução + nome YHWH + qualidade + efeito. A seção final muda para primeira pessoa e transforma teologia em oração."},
 {n:5,label:"Observe o ritmo e as mudanças de tamanho",technical:"Escansão",body:"A principal observação formal é o contraste: a revelação na criação é ampla e variada; a revelação na Palavra é ordenada e repetitiva. As seis linhas regulares sobre a instrução comunicam clareza e precisão. A forma apoia, sem provar sozinha, a diferença entre revelação geral e especial."},
 {n:6,label:"Veja como uma linha responde à outra",technical:"Paralelismo",body:"O paralelismo conduz da criação à consciência.",items:["vv. 1–4: céus → firmamento; dia → noite; ausência de fala audível → mensagem que alcança toda a terra.","vv. 4–6: sol como noivo → sol como herói; alegria e força descrevem seu curso.","vv. 7–10: instrução perfeita → restaura; testemunho fiel → dá sabedoria; preceitos retos → alegram; mandamento puro → ilumina; temor limpo → permanece; juízos verdadeiros → são justos.","vv. 11–14: Palavra adverte → pecado é reconhecido → servo pede preservação → palavras e meditação são oferecidas a Deus."]},
 {n:7,label:"Perceba as repetições e imagens importantes",technical:"Recursos poéticos",body:"O sol, noivo e guerreiro, é criatura obediente, não divindade. No painel da Palavra, seis sinônimos, seis qualidades e seis efeitos criam regularidade. O final liga ‘palavras da boca’ e ‘meditação do coração’, mostrando que revelação recebida deve transformar interior e exterior."},
 {n:8,label:"Separe os grandes blocos",technical:"Estrofes",body:"Três blocos são sustentados por vocabulário, sintaxe e mudança de pessoa.",items:["vv. 1–6 — criação fala de Deus.","vv. 7–10 — Palavra nomeia e instrui sobre YHWH.","vv. 11–14 — o servo responde em santidade e oração."]},
 {n:9,label:"Veja o desenho do Salmo inteiro",technical:"Macroestrutura",body:"Dois painéis de revelação convergem numa resposta pessoal. O universo anuncia; a Palavra articula; o servo se examina. O salmo não opõe natureza e Escritura: mostra que a revelação geral torna Deus conhecido e a Palavra da aliança o torna conhecido de modo moral e pactualmente específico."},
 {n:10,label:"Note o que foge do padrão",technical:"Desvios significativos",body:"A mudança de forma no v. 7 é o maior desvio: de poesia variada sobre o céu para fórmulas extremamente regulares sobre a Palavra. O segundo desvio é o salto para ‘quem há que possa discernir as próprias faltas?’, onde a contemplação se torna confissão."},
 {n:11,label:"Resuma a mensagem em uma frase",technical:"Proposição",body:"O Deus cuja glória é anunciada por toda a criação se dá a conhecer com clareza moral em sua Palavra, levando o servo a passar da contemplação do mundo ao exame do coração e à oração por uma vida aceitável diante dele."},
 {n:12,label:"Coloque o Salmo no conjunto da Bíblia",technical:"Situação canônica e cristológica",body:"Romanos 10:18 reutiliza a linguagem do alcance universal do v. 4 no contexto da proclamação. A leitura reformada reconhece aqui a distinção entre revelação geral e especial. Cristo não precisa ser encontrado por alegoria no sol; canonicamente, todas as coisas foram criadas por meio do Filho e a Palavra culmina nele, o Mediador que também purifica o servo culpado.",items:["A criação torna Deus conhecido, mas não substitui a Palavra redentiva.","A Palavra não é mero conteúdo: ela restaura, alegra, ilumina e julga.","O objetivo final do estudo é oração e santidade."]}
 ],
 theology:["Revelação geral é real, universal e suficiente para manifestar Deus, mas não substitui o evangelho.","Revelação especial é clara, pactual e moralmente formadora.","A suficiência da Escritura leva ao autoexame, não ao orgulho bibliológico.","Cristo é o Mediador em quem criação e redenção encontram seu centro canônico."],
 sermon:{idea:"O Deus que fala no céu fala ainda mais claramente em sua Palavra para levar nosso coração à santidade.",need:"Podemos admirar a criação sem conhecer o Criador e estudar a Bíblia sem permitir que ela examine nossos pecados.",movements:[{title:"Escute a criação",vv:"vv. 1–6",point:"O mundo não é silencioso acerca da glória do Criador."},{title:"Receba a Palavra que dá forma ao conhecimento",vv:"vv. 7–10",point:"A revelação pactual é clara, ordenada e transformadora."},{title:"Deixe a revelação chegar ao coração",vv:"vv. 11–14",point:"O objetivo é confissão, preservação e adoração aceitável."}],climax:"A passagem do céu para a Palavra no v. 7 e da Palavra para o coração no v. 12.",gospel:"A Palavra revela nosso pecado e nos conduz ao Redentor; em Cristo, o Deus que se revela também provê expiação e renovação.",applications:["contemplar criação como criatura e não como divindade","ler a Escritura buscando transformação e não apenas informação","orar regularmente os vv. 12–14 como resposta ao estudo"]}
},
"20":{
 titleVerse:true,
 sources:["Texto Massorético","Calvino, Comentário dos Salmos 1–35","aliança davídica","A Medida do Louvor, índice de salmos régios"],
 steps:[
 {n:1,label:"Confira o texto que será estudado",technical:"Texto e variantes",body:"A sobrescrição o chama de salmo de Davi. O cenário mais provável é oração litúrgica pelo rei antes de batalha, embora não seja possível identificar uma guerra específica. O final possui uma questão de pontuação/tradução sobre ‘ó Rei’ e ‘responde-nos’, mas o sentido geral permanece: a comunidade pede que o Senhor salve o rei e responda ao povo."},
 {n:2,label:"Ouça o Salmo como poesia hebraica",technical:"Leitura e cantilação",body:"Ouça uma série de votos e pedidos dirigidos ao rei nos vv. 1–5, depois a mudança para certeza no v. 6, o contraste memorável do v. 7 e o fechamento em oração comunitária."},
 {n:3,label:"Veja onde cada verso se divide",technical:"Cólons e acentos",body:"Quatro movimentos são claros.",items:["vv. 1–5 — intercessão da comunidade pelo rei.","v. 6 — declaração de certeza de que Deus salva seu ungido.","vv. 7–8 — contraste entre armamentos e o nome do Senhor.","v. 9 — pedido final de salvação e resposta."]},
 {n:4,label:"Confirme se essas divisões fazem sentido",technical:"Sintaxe e paralelismo",body:"Os primeiros versos usam formas de desejo: que Deus responda, proteja, envie socorro, lembre ofertas e conceda propósitos. O v. 6 muda para ‘agora sei’, marcando passagem de intercessão para confiança. O v. 7 contrasta dois objetos de confiança por meio de ‘uns… outros… nós’."},
 {n:5,label:"Observe o ritmo e as mudanças de tamanho",technical:"Escansão",body:"A repetição de votos nos primeiros versos produz cadência litúrgica. O v. 7 se destaca pela formulação equilibrada e fácil de memorizar, funcionando como centro confessional. O final volta à brevidade de uma oração."},
 {n:6,label:"Veja como uma linha responde à outra",technical:"Paralelismo",body:"Os pares ligam culto, batalha e confiança.",items:["vv. 1–2: resposta no dia da angústia → proteção do nome → socorro do santuário.","vv. 3–5: Deus lembra culto → concede desejo correto → povo celebra a salvação.","v. 6: ungido é salvo → resposta vem do céu com poder.","vv. 7–8: carros e cavalos → nome do Senhor; eles caem → nós nos levantamos.","v. 9: salva o rei → responde ao povo."]},
 {n:7,label:"Perceba as repetições e imagens importantes",technical:"Recursos poéticos",body:"Nome do Senhor, santuário, ungido, mão direita, carros e cavalos organizam a teologia. O salmo não despreza meios militares em si; recusa torná-los a base da confiança. O ‘nome’ representa o caráter revelado do Deus da aliança."},
 {n:8,label:"Separe os grandes blocos",technical:"Estrofes",body:"Quatro blocos aparecem pela mudança de voz e função.",items:["vv. 1–5 — oração pelo rei.","v. 6 — certeza.","vv. 7–8 — confissão de confiança.","v. 9 — súplica final."]},
 {n:9,label:"Veja o desenho do Salmo inteiro",technical:"Macroestrutura",body:"A comunidade cerca o rei com oração e coloca a guerra sob o governo de Deus. O centro não é a capacidade do rei, mas o nome do Senhor. O salmo 21 funciona como par posterior de agradecimento pela vitória."},
 {n:10,label:"Note o que foge do padrão",technical:"Desvios significativos",body:"‘Agora sei’ no v. 6 é a virada. O v. 7, por sua antítese simples, condensa toda a teologia do poema e se destaca como frase memorável. A estrutura desloca a confiança de recursos visíveis para o Deus invisível que responde do céu."},
 {n:11,label:"Resuma a mensagem em uma frase",technical:"Proposição",body:"O povo de Deus pode usar meios legítimos e interceder por seus líderes, mas sua esperança decisiva deve permanecer no nome do Senhor, que salva seu ungido e responde do céu."},
 {n:12,label:"Coloque o Salmo no conjunto da Bíblia",technical:"Situação canônica e cristológica",body:"Como salmo régio, ele pressupõe a aliança davídica e prepara o caminho para o Rei messiânico. A igreja não deve transplantar o texto para uma nação moderna nem tratar líderes civis como ‘ungidos’ no mesmo sentido davídico. Em Cristo, o verdadeiro Rei venceu de modo decisivo e seu povo ora sob sua autoridade, não para sacralizar guerras nacionais.",items:["Meios são legítimos; confiança idólatra nos meios não é.","O rei da aliança aponta para Cristo.","A missão da igreja não é uma guerra territorial davídica."]}
 ],
 theology:["Deus governa meios e resultados.","Intercessão comunitária é parte da vida pactual.","A aliança davídica encontra seu centro em Cristo, não em governantes civis modernos.","Fé não exige desprezar recursos; exige não absolutizá-los."],
 sermon:{idea:"Use os meios que Deus dá, mas não entregue a eles a confiança que pertence ao nome do Senhor.",need:"Transformamos tecnologia, dinheiro, influência, instituições e liderança em ‘carros e cavalos’ modernos.",movements:[{title:"Cerque a missão com oração",vv:"vv. 1–5",point:"O rei e o povo dependem do socorro de Deus."},{title:"Deixe a certeza nascer do caráter de Deus",vv:"v. 6",point:"A confiança muda quando Deus é reconhecido como salvador do seu ungido."},{title:"Escolha onde repousa sua confiança",vv:"vv. 7–9",point:"Meios podem ser usados; o nome do Senhor deve ser lembrado."}],climax:"‘Uns confiam em carros, outros em cavalos; nós, porém, nos gloriaremos em o nome do Senhor’ (v. 7).",gospel:"Jesus é o Rei ungido que venceu não pela lógica dos impérios, mas pela cruz e ressurreição; nele a igreja aprende uma confiança que não depende de poder visível.",applications:["identificar nossos equivalentes de carros e cavalos","orar por líderes sem messianizá-los","avaliar sucesso pelo reino de Cristo e não apenas por poder disponível"]}
}
});
