window.MANUAL_ANALYSES=window.MANUAL_ANALYSES||{};
Object.assign(window.MANUAL_ANALYSES,{
"21":{
 titleVerse:true,
 sources:["Texto Massorético","Calvino, Comentário dos Salmos 1–35","aliança davídica de 2 Samuel 7","A Medida do Louvor, índice de salmos régios"],
 steps:[
 {n:1,label:"Confira o texto que será estudado",technical:"Texto e variantes",body:"A sobrescrição o apresenta como salmo de Davi. Ele forma um par natural com o Salmo 20: ali o povo ora antes da batalha; aqui agradece pela vitória concedida ao rei. Nos vv. 8–12 há mudança de interlocutor que pode ser entendida como fala ao rei sob a ação de Deus; a teologia do poema continua sendo que a vitória real depende do Senhor."},
 {n:2,label:"Ouça o Salmo como poesia hebraica",technical:"Leitura e cantilação",body:"Ouça a repetição de alegria, desejo, coroa, vida e confiança nos vv. 1–7. Depois o tom muda para juízo contra os inimigos e termina com a congregação exaltando a força do Senhor."},
 {n:3,label:"Veja onde cada verso se divide",technical:"Cólons e acentos",body:"Três movimentos dominam o salmo.",items:["vv. 1–7 — gratidão pela vitória e pelas bênçãos dadas ao rei.","vv. 8–12 — certeza de que os inimigos não frustrarão o governo estabelecido por Deus.","v. 13 — louvor final à força do Senhor."]},
 {n:4,label:"Confirme se essas divisões fazem sentido",technical:"Sintaxe e paralelismo",body:"Os primeiros versos falam de Deus em segunda pessoa e do rei em terceira: ‘tu lhe deste’. O v. 7 fornece a base da estabilidade: o rei confia no Senhor e no amor fiel do Altíssimo. O final volta ao imperativo de louvor comunitário."},
 {n:5,label:"Observe o ritmo e as mudanças de tamanho",technical:"Escansão",body:"A primeira parte tem tom celebrativo e cumulativo, empilhando benefícios. A seção de juízo é mais agressiva e verbal. O verso final volta a uma forma litúrgica curta, recolocando a atenção na força de Deus, e não na habilidade do rei."},
 {n:6,label:"Veja como uma linha responde à outra",technical:"Paralelismo",body:"O paralelismo amplia a gratidão e depois descreve a derrota dos inimigos.",items:["vv. 1–2: força de Deus → alegria do rei; desejo do coração → pedido dos lábios.","vv. 3–6: bênçãos → coroa → vida → glória → majestade; dons se acumulam.","v. 7: confiança no Senhor → amor fiel do Altíssimo → estabilidade.","vv. 8–12: inimigos encontrados → juízo → planos frustrados → fuga.","v. 13: exaltação da força → canto do poder de Deus."]},
 {n:7,label:"Perceba as repetições e imagens importantes",technical:"Recursos poéticos",body:"Coroa, vida longa, glória, bênção e mão poderosa formam linguagem régia. O pedido por ‘vida’ e a linguagem ‘para todo o sempre’ ultrapassam uma vitória isolada e se conectam naturalmente à continuidade da casa davídica. O centro espiritual, porém, é confiança no hesed do Altíssimo."},
 {n:8,label:"Separe os grandes blocos",technical:"Estrofes",body:"A mudança de assunto e tom sustenta três blocos.",items:["vv. 1–7 — bênção e confiança do rei.","vv. 8–12 — juízo sobre os inimigos.","v. 13 — doxologia da comunidade."]},
 {n:9,label:"Veja o desenho do Salmo inteiro",technical:"Macroestrutura",body:"O salmo começa com o rei alegrando-se na força de Deus e termina com o povo exaltando essa mesma força. Assim, toda a vitória fica emoldurada pela ação divina. O Salmo 20 pediu; o Salmo 21 agradece."},
 {n:10,label:"Note o que foge do padrão",technical:"Desvios significativos",body:"A linguagem de duração no v. 4 e a bênção permanente nos vv. 6–7 ampliam o horizonte além de um dia de batalha. O final também corrige qualquer tendência a glorificar o rei: a última exaltação é dirigida ao Senhor."},
 {n:11,label:"Resuma a mensagem em uma frase",technical:"Proposição",body:"O rei se alegra porque a vitória, a vida e a estabilidade são dádivas do Senhor, cuja fidelidade sustenta o trono e frustra a oposição, levando o povo a louvar a força de Deus."},
 {n:12,label:"Coloque o Salmo no conjunto da Bíblia",technical:"Situação canônica e cristológica",body:"Como salmo régio, ele pertence à linha da aliança davídica. A linguagem de vida, glória e permanência encontra sua realização plena no Rei ressuscitado, Jesus. A igreja não deve aplicar a vitória militar do rei diretamente a projetos nacionais ou pessoais; ela celebra o reinado de Cristo e a derrota final de tudo que se opõe a Deus.",items:["O rei histórico recebe a vitória; não a produz de modo autônomo.","A permanência da casa de Davi prepara o horizonte messiânico.","O louvor final impede a idolatria do líder."]}
 ],
 theology:["Toda autoridade legítima permanece dependente do Senhor.","Hesed, o amor fiel da aliança, é a base da estabilidade do rei.","A promessa davídica se cumpre no Rei que venceu a morte.","Vitória do Messias não deve ser confundida com triunfalismo político da igreja."],
 sermon:{idea:"A vitória do Rei é dádiva da fidelidade de Deus, por isso a glória final pertence ao Senhor.",need:"Somos rápidos para atribuir sucesso à competência humana e transformar líderes vitoriosos em salvadores.",movements:[{title:"Receba a vitória como presente",vv:"vv. 1–6",point:"Desejos, vida, coroa e glória são apresentados como dádivas de Deus."},{title:"Descanse na fidelidade que sustenta",vv:"v. 7",point:"A estabilidade do rei repousa no amor pactual do Altíssimo."},{title:"Devolva a glória ao verdadeiro forte",vv:"vv. 8–13",point:"O juízo pertence a Deus e a comunidade termina cantando seu poder."}],climax:"‘O rei confia no Senhor e pela misericórdia do Altíssimo jamais vacilará’ (v. 7).",gospel:"Jesus, Filho de Davi, recebeu do Pai a vitória definitiva na ressurreição e reina para sempre; nele a igreja celebra um triunfo que não depende de um governante terreno.",applications:["agradecer por resultados sem idolatrar competências","avaliar liderança pela dependência de Deus","reservar a esperança final para o reinado de Cristo"]}
},
"22":{
 titleVerse:true,
 sources:["A Medida do Louvor, cap. 30","Texto Massorético","Mateus 27; Marcos 15","Hebreus 2:12","Calvino, Comentário dos Salmos 1–35"],
 steps:[
 {n:1,label:"Confira o texto que será estudado",technical:"Texto e variantes",body:"A sobrescrição contém uma indicação musical tradicionalmente relacionada à ‘corça da manhã’, cujo significado exato é incerto. Há uma questão textual conhecida no v. 16: o Texto Massorético tem uma forma difícil, tradicionalmente lida ‘como leão, minhas mãos e pés’, enquanto testemunhos antigos sustentam uma leitura verbal que está por trás de ‘traspassaram/perfuraram’. A ARA segue essa tradição. A cristologia do salmo não depende apenas desse verso: o Novo Testamento usa explicitamente o grito inicial, a zombaria, as vestes e o louvor entre irmãos.",items:["A numeração desta página segue a ARA.","Evitar tratar uma variante discutida como se fosse argumento único e incontestável."]},
 {n:2,label:"Ouça o Salmo como poesia hebraica",technical:"Leitura e cantilação",body:"Ouça a alternância da primeira grande parte: queixa, lembrança de Deus, queixa, lembrança de Deus, descrição do sofrimento e pedido. Depois perceba a mudança abrupta para louvor. O salmo começa com ‘meu Deus’ e termina com anúncio às gerações."},
 {n:3,label:"Veja onde cada verso se divide",technical:"Cólons e acentos",body:"Por ser longo, a análise estrutural deve trabalhar com blocos e depois observar versos-chave.",items:["vv. 1–2 — grito de abandono e clamor sem resposta percebida.","vv. 3–5 — ‘contudo, tu’: santidade de Deus e memória dos pais que confiaram.","vv. 6–8 — humilhação e zombaria pública.","vv. 9–11 — ‘tu me tiraste do ventre’: relação com Deus desde o nascimento.","vv. 12–18 — cerco de animais, desintegração corporal e vestes divididas.","vv. 19–21 — pedido final urgente de presença e livramento.","vv. 22–26 — louvor na assembleia e cuidado com os aflitos.","vv. 27–31 — todas as nações e gerações reconhecem o reinado do Senhor."]},
 {n:4,label:"Confirme se essas divisões fazem sentido",technical:"Sintaxe e paralelismo",body:"A seção de lamento é costurada por pronomes enfáticos dirigidos a Deus: ‘tu és santo’, ‘tu me tiraste do ventre’, ‘tu, Senhor, não te afastes’. O sofredor agarra-se ao ‘tu’ justamente quando sente a ausência de Deus. Entre o pedido final e o louvor aparece uma resposta pressuposta, não narrada em detalhes."},
 {n:5,label:"Observe o ritmo e as mudanças de tamanho",technical:"Escansão",body:"A extensão do salmo permite ritmos locais. O grito inicial é forte e compacto; as descrições do sofrimento se alongam; a segunda metade se amplia geográfica e temporalmente. Mais importante que uma média é a enorme mudança de função entre lamento e louvor: o poema passa do indivíduo abandonado para as nações e gerações futuras.",items:["A análise do livro anexo recomenda macroestrutura em salmos longos, em vez de forçar uma métrica única.","O salto para o louvor é estruturalmente mais importante que pequenas diferenças de contagem."]},
 {n:6,label:"Veja como uma linha responde à outra",technical:"Paralelismo",body:"O paralelismo alterna sofrimento e memória de Deus até a virada.",items:["vv. 1–2: abandono percebido → clamor dia e noite.","vv. 3–5: Deus santo → pais confiaram → foram livrados.","vv. 6–8: identidade humilhada → desprezo → zombadores usam a própria confiança do justo contra ele.","vv. 9–11: Deus no nascimento → confiança desde o ventre → pedido de proximidade.","vv. 12–18: touros/leão/cães → corpo dissolvido → mãos e pés → vestes; sofrimento se torna total.","vv. 19–21: não te afastes → livra da espada, cães, leão e bois.","vv. 22–26: anúncio aos irmãos → louvor da congregação → aflitos comem e se saciam.","vv. 27–31: confins da terra → famílias das nações → mortos e vivos → geração ainda não nascida."]},
 {n:7,label:"Perceba as repetições e imagens importantes",technical:"Recursos poéticos",body:"‘Meu Deus’ mantém a relação dentro da queixa. Animais ameaçadores, ossos, coração derretido, língua seca, vestes e pó tornam o sofrimento concreto. Na segunda metade, os círculos se expandem: irmãos, congregação, pobres, nações e gerações. O movimento é da solidão para a comunidade universal."},
 {n:8,label:"Separe os grandes blocos",technical:"Estrofes",body:"Duas metades grandes contêm subdivisões claras.",items:["vv. 1–21 — lamento e petição, alternando ausência percebida e memória da fidelidade de Deus.","vv. 22–31 — louvor, testemunho, saciedade dos pobres, adoração das nações e anúncio às gerações."]},
 {n:9,label:"Veja o desenho do Salmo inteiro",technical:"Macroestrutura",body:"O salmo começa com abandono e termina com obra realizada e anunciada. A resposta divina não recebe uma narrativa longa; o poema simplesmente atravessa para o louvor. Essa ausência de explicação faz a virada ainda mais forte: a salvação é conhecida por seus efeitos — congregação reunida, pobres alimentados e nações adorando."},
 {n:10,label:"Note o que foge do padrão",technical:"Desvios significativos",body:"A transição entre pedido e louvor é uma das mudanças mais abruptas do Saltério. Outro desvio importante é a expansão final: o problema era de um indivíduo, mas a resposta termina alcançando o mundo e o futuro. Esses dois dados devem organizar a pregação."},
 {n:11,label:"Resuma a mensagem em uma frase",technical:"Proposição",body:"O justo que se sente abandonado continua chamando Deus de ‘meu Deus’ até que a resposta transforme seu sofrimento em testemunho, e o livramento de um homem se expanda em louvor entre irmãos, pobres, nações e gerações futuras."},
 {n:12,label:"Coloque o Salmo no conjunto da Bíblia",technical:"Situação canônica e cristológica",body:"Aqui a relação com Cristo é explicitamente governada pelo Novo Testamento. Jesus toma o grito inicial na cruz; os evangelhos ecoam a zombaria e a divisão das vestes; Hebreus 2:12 coloca o v. 22 na boca do Filho que chama os santificados de irmãos. Portanto, Cristo não é acrescentado ao salmo por criatividade: a Escritura o identifica como o justo sofredor que leva essa oração à sua plenitude.",items:["Primeiro reconhecer o sofrimento real de um justo davídico.","Depois seguir os próprios Evangelhos e Hebreus.","A igreja ora o salmo depois de Cristo e unida a ele, não como se repetisse sua obra expiatória."]}
 ],
 theology:["A fé pode manter a palavra ‘meu’ mesmo quando a experiência diz ‘abandonado’.","A cruz é o cumprimento máximo do justo sofredor e não mera ilustração emocional.","O livramento messiânico cria uma comunidade e alcança as nações.","Sofrimento e missão se ligam: a resposta de Deus torna-se testemunho público."],
 sermon:{idea:"O abandono sentido pelo justo não rompe a fidelidade de Deus; em Cristo, a resposta transforma o grito em louvor para as nações e gerações.",need:"Na dor, concluímos que silêncio significa ruptura da relação e que nosso sofrimento não pode servir a nenhum propósito além de nós mesmos.",movements:[{title:"Continue dizendo ‘meu Deus’ no escuro",vv:"vv. 1–11",point:"A queixa permanece pactual porque o sofredor continua falando com Deus e lembrando sua história."},{title:"Leve a Deus o sofrimento inteiro",vv:"vv. 12–21",point:"O poema não espiritualiza a dor; corpo, vergonha, violência e morte são nomeados."},{title:"Veja a resposta tornar-se anúncio",vv:"vv. 22–31",point:"O livramento se expande para irmãos, pobres, nações e gerações."}],climax:"A virada do pedido para ‘a meus irmãos declararei o teu nome’ (v. 22).",gospel:"Jesus orou o início na cruz e Hebreus coloca o louvor do v. 22 em sua boca; sua morte e ressurreição transformam abandono judicial em salvação compartilhada com seus irmãos.",applications:["orar o sofrimento sem censura devocional","ler a cruz como evento objetivo de redenção, não só exemplo de dor","transformar livramentos recebidos em testemunho e serviço"]}
},
"23":{
 titleVerse:true,
 sources:["A Medida do Louvor, cap. 25","Texto Massorético","Ezequiel 34","João 10:11","Calvino, Comentário dos Salmos 1–35"],
 steps:[
 {n:1,label:"Confira o texto que será estudado",technical:"Texto e variantes",body:"A sobrescrição é simples: salmo de Davi. A imagem do pastor no mundo antigo também era imagem de rei e governante, portanto ‘o Senhor é meu pastor’ é mais que uma cena rural: o Grande Rei assume cuidado pessoal. No v. 6, a forma hebraica tradicionalmente traduzida ‘habitarei’ tem história interpretativa complexa, mas o sentido converge na permanência junto ao Senhor."},
 {n:2,label:"Ouça o Salmo como poesia hebraica",technical:"Leitura e cantilação",body:"Ouça a mudança mais importante do salmo: nos vv. 1–3 Davi fala sobre Deus — ‘ele’. No v. 4, dentro do vale, começa a falar diretamente com Deus — ‘tu’. No v. 6 volta a mencionar ‘a casa do Senhor’. O salmo vai de teologia para oração e volta à teologia."},
 {n:3,label:"Veja onde cada verso se divide",technical:"Cólons e acentos",body:"A divisão poética mostra uma curva de expansão.",items:["vv. 1–2 — pastor, provisão, repouso e condução.","v. 3 — restauração e caminhos justos por causa do nome de Deus.","v. 4 — vale, ausência de medo e presença direta do Pastor.","v. 5 — mesa diante de inimigos, unção e cálice cheio.","v. 6 — bondade, amor fiel e casa do Senhor."]},
 {n:4,label:"Confirme se essas divisões fazem sentido",technical:"Sintaxe e paralelismo",body:"A gramática confirma o centro: terceira pessoa em vv. 1–3, segunda pessoa em vv. 4–5 e retorno à terceira no final. Além disso, a primeira pessoa aparece repetidamente como objeto do cuidado: Deus faz repousar, conduz, restaura, guia, consola, prepara e unge. O sujeito ativo é majoritariamente Deus."},
 {n:5,label:"Observe o ritmo e as mudanças de tamanho",technical:"Escansão",body:"O salmo começa compacto, cresce no vale e na mesa e volta a contrair no fechamento. A expansão máxima coincide com perigo e presença. Isso corrige uma leitura sentimental: o poema não promete ausência de ameaça; ele dá mais espaço justamente ao lugar em que o Pastor está ‘comigo’."},
 {n:6,label:"Veja como uma linha responde à outra",technical:"Paralelismo",body:"As linhas desenvolvem o cuidado do Pastor-Rei.",items:["v. 1: identidade do Pastor → suficiência.","v. 2: repousar em pastos → ser conduzido a águas de descanso.","v. 3: restaurar a vida → guiar em caminhos corretos → agir por causa do próprio nome.","v. 4: vale escuro → não temer → ‘tu estás comigo’ → vara e cajado consolam.","v. 5: inimigos presentes → mesa preparada → cabeça ungida → cálice abundante.","v. 6: inimigos deixam de ser os perseguidores centrais; bondade e amor fiel é que ‘perseguem’ o salmista → casa do Senhor como destino."]},
 {n:7,label:"Perceba as repetições e imagens importantes",technical:"Recursos poéticos",body:"Pastor e anfitrião real são as duas imagens maiores. Vara e cajado unem proteção, governo e correção. O verbo do v. 6 costuma ser suavizado como ‘seguir’, mas tem força de ‘perseguir’: Davi, antes cercado por adversários, passa a ser perseguido pela bondade e pelo amor fiel de Deus."},
 {n:8,label:"Separe os grandes blocos",technical:"Estrofes",body:"A mudança de pessoa, assunto e cenário permite cinco blocos que podem ser lidos de forma concêntrica.",items:["vv. 1–2 — provisão do Pastor.","v. 3 — restauração e direção.","v. 4 — presença no perigo.","v. 5 — hospitalidade e honra diante dos inimigos.","v. 6 — bondade e morada."]},
 {n:9,label:"Veja o desenho do Salmo inteiro",technical:"Macroestrutura",body:"A leitura concêntrica coloca o v. 4 no centro: provisão → direção → presença → mesa → casa. O ponto alto não é o pasto, mas ‘tu estás comigo’. A abundância do final nasce da presença do Pastor dentro da realidade de inimigos e vale."},
 {n:10,label:"Note o que foge do padrão",technical:"Desvios significativos",body:"Dois desvios convergem: o poema se expande no vale e a gramática muda para ‘tu’. Como forma, sintaxe e sentido apontam juntos, esse é um centro interpretativo seguro. O outro destaque é a inversão do verbo ‘perseguir’ no v. 6, que troca adversários por bondade e amor fiel."},
 {n:11,label:"Resuma a mensagem em uma frase",technical:"Proposição",body:"Porque o Senhor é o Pastor-Rei do seu povo, ele provê, restaura e guia; e sua suficiência se mostra especialmente no perigo, onde sua presença transforma o vale e os inimigos em caminho para a mesa, a bondade e a casa de Deus."},
 {n:12,label:"Coloque o Salmo no conjunto da Bíblia",technical:"Situação canônica e cristológica",body:"Ezequiel 34 promete que Deus mesmo pastoreará seu povo e denuncia pastores infiéis; João 10 mostra Jesus dizendo ‘Eu sou o bom pastor’. A conexão é canônica e pactual, não alegórica: pastos não ‘significam sacramentos’, vara não ‘significa cruz’. Cristo é o Pastor prometido que dá a vida pelas ovelhas e as conduz à presença de Deus.",items:["Não prometer uma vida sem vale ou inimigos.","A graça aparece na predominância das ações de Deus sobre o salmista.","A aplicação cristã nasce da identidade de Jesus como o Bom Pastor."]}
 ],
 theology:["Providência não é ausência de perigo, mas presença e governo de Deus dentro dele.","A graça é encenada na gramática: Deus age, o crente recebe e responde.","Disciplina e consolo podem estar unidos no cuidado do Pastor.","Cristo cumpre a promessa de Deus pastorear pessoalmente seu povo."],
 sermon:{idea:"A suficiência do Pastor não se prova pela ausência do vale, mas por sua presença conosco dentro dele.",need:"Queremos usar Deus para evitar o vale e, quando o vale chega, concluímos que o Pastor falhou.",movements:[{title:"Receba o cuidado do Pastor",vv:"vv. 1–3",point:"Provisão, repouso, restauração e direção vêm de Deus."},{title:"Descubra a presença no vale",vv:"v. 4",point:"O pronome muda porque a ameaça transforma teologia em oração."},{title:"Veja o Pastor transformar perseguição em comunhão",vv:"vv. 5–6",point:"Mesa, bondade e casa são o destino do cuidado pactual."}],climax:"‘Porque tu estás comigo’ (v. 4).",gospel:"Jesus é o Bom Pastor que atravessou a morte, deu a vida pelas ovelhas e vive para conduzi-las à casa do Pai.",applications:["medir a fidelidade de Deus por sua presença, não por conforto","receber correção e sustentação como partes do cuidado pastoral","orar diretamente a Deus no vale em vez de apenas falar sobre ele"]}
},
"24":{
 titleVerse:true,
 sources:["Texto Massorético","Calvino, Comentário dos Salmos 1–35","Salmo 15 como paralelo de entrada no santuário","Hebreus como horizonte canônico de acesso ao santuário"],
 steps:[
 {n:1,label:"Confira o texto que será estudado",technical:"Texto e variantes",body:"A sobrescrição o identifica como salmo de Davi, mas não informa ocasião histórica. É comum associá-lo a uma procissão da arca ou entrada litúrgica em Sião; isso é plausível, não demonstrável. A análise deve deixar o texto falar: o Criador possui a terra, o adorador deve ser santo e o Rei da Glória entra."},
 {n:2,label:"Ouça o Salmo como poesia hebraica",technical:"Leitura e cantilação",body:"Ouça três cenas bem diferentes: declaração cósmica, pergunta litúrgica e diálogo com portas personificadas. No fim, a pergunta ‘quem é o Rei da Glória?’ é repetida e respondida com o nome do Senhor."},
 {n:3,label:"Veja onde cada verso se divide",technical:"Cólons e acentos",body:"Três painéis estruturam o poema.",items:["vv. 1–2 — a terra inteira pertence ao Senhor criador.","vv. 3–6 — quem pode subir ao monte santo? Retrato do adorador e da geração que busca Deus.","vv. 7–10 — portas são chamadas a se abrir para a entrada do Rei da Glória."]},
 {n:4,label:"Confirme se essas divisões fazem sentido",technical:"Sintaxe e paralelismo",body:"O primeiro painel é declarativo. O segundo começa com duas perguntas e responde com uma lista ética. O terceiro muda para imperativos e diálogo responsivo: ‘levantai’ → ‘quem é?’ → ‘o Senhor’. Essas mudanças gramaticais são fronteiras seguras."},
 {n:5,label:"Observe o ritmo e as mudanças de tamanho",technical:"Escansão",body:"O salmo alterna declaração, catequese e aclamação. O terceiro painel se torna mais repetitivo e responsorial, adequado a uma cena litúrgica. A repetição final dá solenidade à identificação do Rei."},
 {n:6,label:"Veja como uma linha responde à outra",technical:"Paralelismo",body:"Os pares ampliam posse, santidade e realeza.",items:["vv. 1–2: terra e plenitude → mundo e habitantes → fundação sobre mares e rios.","vv. 3–4: subir ao monte → permanecer no lugar santo → mãos limpas + coração puro + fala fiel.","vv. 5–6: bênção e justiça recebidas → geração que busca a face de Deus.","vv. 7–10: portas se levantam → Rei entra; pergunta repetida → respostas crescentes sobre o Senhor forte, guerreiro e Senhor dos Exércitos."]},
 {n:7,label:"Perceba as repetições e imagens importantes",technical:"Recursos poéticos",body:"Mar, monte, mãos, coração, face e portas conduzem o leitor do cosmos ao santuário. As portas são personificadas e recebem ordens como se toda a cidade precisasse se ajustar à chegada do Rei. ‘Rei da Glória’ é repetido para fixar a identidade daquele que entra."},
 {n:8,label:"Separe os grandes blocos",technical:"Estrofes",body:"Três blocos são confirmados por mudança de cenário e forma.",items:["vv. 1–2 — Criador e proprietário universal.","vv. 3–6 — santidade do adorador.","vv. 7–10 — entrada do Rei da Glória."]},
 {n:9,label:"Veja o desenho do Salmo inteiro",technical:"Macroestrutura",body:"O poema vai do domínio universal de Deus para a aproximação humana e volta à entrada do próprio Deus como Rei. A pergunta ‘quem pode subir?’ e a pergunta ‘quem é o Rei?’ colocam adorador e Deus em contraste: a santidade é exigida porque o visitante principal é o Rei santo."},
 {n:10,label:"Note o que foge do padrão",technical:"Desvios significativos",body:"A transformação do terceiro painel em diálogo repetido é o maior destaque formal. O outro é a resposta ética no centro: em um salmo sobre o Rei da Glória, a preparação para sua presença aparece em mãos, coração e lealdade, não em espetáculo religioso."},
 {n:11,label:"Resuma a mensagem em uma frase",technical:"Proposição",body:"O Senhor que possui toda a criação é o Rei da Glória que entra em seu santuário, e sua presença chama para perto uma geração marcada por mãos limpas, coração puro e busca sincera da face de Deus."},
 {n:12,label:"Coloque o Salmo no conjunto da Bíblia",technical:"Situação canônica e cristológica",body:"A tradição cristã frequentemente relaciona o último painel à ascensão de Cristo. Isso pode ser pregado como trajetória tipológica e canônica: o Rei vitorioso e perfeitamente santo entra na presença de Deus e abre caminho para seu povo. Não é necessário afirmar que as ‘portas’ eram uma previsão lexical direta da ascensão. Cristo é também o único adorador que cumpre perfeitamente os requisitos do centro.",items:["Começar pelo sentido litúrgico e régio do salmo.","Seguir a teologia bíblica do Rei e do santuário até Cristo.","Aplicar santidade como fruto do acesso recebido, não como compra desse acesso."]}
 ],
 theology:["O domínio de Deus é universal, não confinado ao santuário.","Santidade interior e exterior é coerente com a presença do Rei.","Cristo é Rei vitorioso e adorador perfeito.","Acesso a Deus é mediado pela obra de Cristo e produz busca real por pureza."],
 sermon:{idea:"O Rei que possui toda a terra chama para sua presença um povo purificado e abre o caminho que ninguém poderia conquistar por mérito próprio.",need:"Queremos os benefícios da presença de Deus sem a santidade de Deus, ou tentamos comprar acesso por desempenho religioso.",movements:[{title:"Reconheça quem é o dono",vv:"vv. 1–2",point:"Adoração começa com o Criador e Rei de tudo."},{title:"Pergunte quem pode estar diante dele",vv:"vv. 3–6",point:"A presença santa expõe nossa necessidade de pureza integral."},{title:"Receba o Rei da Glória",vv:"vv. 7–10",point:"O centro final é o próprio Senhor que entra como Rei vitorioso."}],climax:"‘Quem é o Rei da Glória?’ — repetido até a resposta final: o Senhor dos Exércitos.",gospel:"Jesus, Rei e homem perfeitamente santo, entrou no santuário celestial por sua própria justiça e conduz consigo um povo purificado por sua obra.",applications:["submeter toda a vida ao Rei que possui a terra","buscar pureza de mãos e coração como fruto da graça","adorar Cristo sem reduzir seu reino a símbolos litúrgicos"]}
},
"25":{
 titleVerse:true,
 sources:["Texto Massorético","Calvino, Comentário dos Salmos 1–35","A Medida do Louvor, índice de acrósticos e lamentos","teologia pactual reformada"],
 steps:[
 {n:1,label:"Confira o texto que será estudado",technical:"Texto e variantes",body:"A sobrescrição o atribui a Davi. O poema é acróstico, embora com algumas irregularidades, e mistura lamento, sabedoria e confissão. A organização alfabética favorece a ideia de oração abrangente: direção, culpa, inimigos, aliança e solidão são colocados diante de Deus."},
 {n:2,label:"Ouça o Salmo como poesia hebraica",technical:"Leitura e cantilação",body:"Ouça a alternância constante entre pedido e ensino. Davi pede que Deus mostre caminhos, lembra a misericórdia, confessa pecado, descreve quem Deus ensina e volta ao sofrimento. O salmo não separa orientação moral de perdão."},
 {n:3,label:"Veja onde cada verso se divide",technical:"Cólons e acentos",body:"Cinco movimentos cobrem a oração.",items:["vv. 1–3 — confiança e pedido para não ser envergonhado.","vv. 4–7 — pedido de direção e perdão à luz da misericórdia antiga de Deus.","vv. 8–10 — declaração de que o Senhor é bom e ensina seus caminhos.","vv. 11–15 — perdão, temor do Senhor, aliança e intimidade pactual.","vv. 16–22 — solidão, angústia, inimigos, integridade e pedido final de redenção de Israel."]},
 {n:4,label:"Confirme se essas divisões fazem sentido",technical:"Sintaxe e paralelismo",body:"Os imperativos ‘faz-me conhecer’, ‘ensina-me’, ‘guia-me’, ‘lembra-te’ e ‘não te lembres’ dominam a primeira metade. Depois frases de sabedoria descrevem como Deus instrui os humildes. O v. 11 volta à primeira pessoa com um pedido de perdão ‘por causa do teu nome’, e o final acumula imperativos de socorro."},
 {n:5,label:"Observe o ritmo e as mudanças de tamanho",technical:"Escansão",body:"O acróstico influencia a forma mais que um metro regular. A repetição de pedidos cria ritmo de dependência. O v. 11 se destaca por concentrar em uma frase a lógica da graça: o nome de Deus é a razão do perdão, apesar de — e justamente diante de — grande culpa."},
 {n:6,label:"Veja como uma linha responde à outra",technical:"Paralelismo",body:"Os pares ligam direção e graça.",items:["vv. 1–3: levantar a alma → confiar → não ser envergonhado.","vv. 4–5: caminhos → veredas → verdade; conhecer → ensinar → guiar.","vv. 6–7: lembrar misericórdias → não lembrar pecados da juventude → lembrar do pecador segundo a bondade.","vv. 8–10: Deus é bom e reto → ensina pecadores e humildes → caminhos são amor e fidelidade para quem guarda aliança.","vv. 11–15: culpa grande → perdão por causa do nome → temor → ensino → comunhão da aliança.","vv. 16–22: solidão e angústia → perdão → proteção → integridade → redenção de todo Israel."]},
 {n:7,label:"Perceba as repetições e imagens importantes",technical:"Recursos poéticos",body:"Caminho, vereda, ensinar, lembrar, temor, aliança e olhos formam a rede central. ‘Meus olhos se elevam continuamente ao Senhor’ retoma a alma levantada do início. O acróstico dá ordem à oração de uma vida que parece desordenada."},
 {n:8,label:"Separe os grandes blocos",technical:"Estrofes",body:"As mudanças entre súplica, sabedoria e nova súplica sugerem cinco blocos.",items:["vv. 1–3 — confiança.","vv. 4–7 — direção e perdão.","vv. 8–10 — caráter do Deus que ensina.","vv. 11–15 — culpa, temor e aliança.","vv. 16–22 — sofrimento e redenção."]},
 {n:9,label:"Veja o desenho do Salmo inteiro",technical:"Macroestrutura",body:"O salmo reúne dois problemas que frequentemente separamos: ‘não sei o caminho’ e ‘sou culpado’. Deus responde como Mestre e Redentor. A oração termina ampliando a experiência pessoal para Israel, mostrando que direção e redenção pertencem ao povo da aliança."},
 {n:10,label:"Note o que foge do padrão",technical:"Desvios significativos",body:"O v. 11 é o centro teológico mais marcante porque interrompe a linguagem geral e confessa ‘minha iniquidade é grande’. O tamanho da culpa não é argumento de mérito; o fundamento é ‘por causa do teu nome’. O último verso também amplia do indivíduo para Israel."},
 {n:11,label:"Resuma a mensagem em uma frase",technical:"Proposição",body:"O pecador que não sabe por onde andar pode pedir ao Deus da aliança tanto perdão quanto direção, porque o Senhor age por causa do próprio nome, ensina os humildes e mantém amor fiel com seu povo."},
 {n:12,label:"Coloque o Salmo no conjunto da Bíblia",technical:"Situação canônica e cristológica",body:"A leitura reformada vê aqui graça pactual, não salvação por desempenho. Cristo é o Mediador da nova aliança em quem culpa é perdoada e a lei é escrita no coração. O crente não pede direção para conquistar aceitação; ele pede porque pertence pela graça ao Deus que perdoa e ensina.",items:["Perdão e santificação não competem.","O nome de Deus, não o valor do penitente, fundamenta o pedido.","Integridade no final é fruto desejado por alguém que acabou de confessar pecado."]}
 ],
 theology:["Graça perdoa e ensina.","Humildade é postura própria do discípulo que conhece a própria culpa.","Aliança envolve verdade e amor fiel, não sentimentalismo sem obediência.","A santificação é resposta pactual à graça recebida."],
 sermon:{idea:"O Deus que perdoa nossa culpa é o mesmo que nos ensina o caminho, e ambos os dons vêm por causa do seu nome.",need:"Ou queremos direção sem arrependimento, ou pensamos que nossa culpa nos desqualifica para aprender a andar com Deus.",movements:[{title:"Levante a alma para o Deus em quem confia",vv:"vv. 1–3",point:"A oração começa com dependência, não autoconfiança."},{title:"Peça perdão e caminho ao mesmo Deus",vv:"vv. 4–15",point:"Misericórdia e instrução estão unidas na aliança."},{title:"Leve toda a angústia à redenção",vv:"vv. 16–22",point:"O pedido pessoal termina no bem do povo de Deus."}],climax:"‘Por causa do teu nome, Senhor, perdoa a minha iniquidade, que é grande’ (v. 11).",gospel:"Em Cristo, Deus honra seu nome perdoando culpados e, pelo Espírito, ensinando-os a andar em seus caminhos.",applications:["confessar culpa sem fugir do discipulado","pedir orientação submetendo-se à Palavra","buscar integridade como fruto da graça e não certificado de perfeição"]}
},
"26":{
 titleVerse:true,
 sources:["Texto Massorético","Calvino, Comentário dos Salmos 1–35","Salmo 25 como contexto próximo","A Medida do Louvor, hermenêutica pactual"],
 steps:[
 {n:1,label:"Confira o texto que será estudado",technical:"Texto e variantes",body:"A sobrescrição o atribui a Davi. A frase ‘julga-me/vindica-me’ e as declarações de integridade devem ser lidas ao lado do Salmo 25, em que Davi confessa grande pecado. Portanto, ‘integridade’ aqui significa lealdade sincera e inocência na causa em questão, não perfeição sem pecado."},
 {n:2,label:"Ouça o Salmo como poesia hebraica",technical:"Leitura e cantilação",body:"Ouça como Davi convida Deus a examiná-lo, depois descreve companhias que evita, aproxima-se do altar, pede para não ser levado com pecadores e termina firme na assembleia bendizendo o Senhor."},
 {n:3,label:"Veja onde cada verso se divide",technical:"Cólons e acentos",body:"Cinco movimentos estruturam o salmo.",items:["vv. 1–3 — pedido de vindicação e exame.","vv. 4–5 — separação da falsidade e da violência.","vv. 6–8 — lavagem simbólica das mãos, altar, gratidão e amor pela casa de Deus.","vv. 9–10 — pedido para não receber o destino dos homens sanguinários.","vv. 11–12 — resolução de andar em integridade, pedido de graça e louvor na assembleia."]},
 {n:4,label:"Confirme se essas divisões fazem sentido",technical:"Sintaxe e paralelismo",body:"Imperativos de exame abrem o texto. A seguir predominam negativas sobre más companhias. Depois verbos de culto e amor pela casa do Senhor. O pedido ‘não colhas minha alma com pecadores’ marca nova seção, e o ‘quanto a mim’ do v. 11 introduz a resolução final."},
 {n:5,label:"Observe o ritmo e as mudanças de tamanho",technical:"Escansão",body:"O ritmo é equilibrado e deliberativo. O centro litúrgico nos vv. 6–8 recebe expansão suficiente para mostrar que integridade não é isolamento moralista; ela deseja adoração e gratidão. O final é estável: pés em terreno plano e louvor na assembleia."},
 {n:6,label:"Veja como uma linha responde à outra",technical:"Paralelismo",body:"As linhas desenham integridade como vida coerente diante de Deus.",items:["vv. 1–3: integridade → confiança → exame de mente e coração → amor fiel diante dos olhos.","vv. 4–5: não sentar com falsos → odiar assembleia dos malfeitores.","vv. 6–8: mãos lavadas → altar → ação de graças → amor pela habitação de Deus.","vv. 9–10: não ser levado com pecadores → suas mãos estão cheias de violência e suborno.","vv. 11–12: andar em integridade → pedir graça → pé firme → bênção pública."]},
 {n:7,label:"Perceba as repetições e imagens importantes",technical:"Recursos poéticos",body:"Mãos aparecem primeiro lavadas e depois, em contraste, cheias de crimes e suborno. Sentar-se com falsos contrasta com estar na assembleia que bendiz Deus. O salmo trabalha com espaços sociais diferentes para mostrar que caráter e pertencimento caminham juntos."},
 {n:8,label:"Separe os grandes blocos",technical:"Estrofes",body:"Cinco blocos aparecem pela mudança de assunto.",items:["vv. 1–3 — exame.","vv. 4–5 — companhias evitadas.","vv. 6–8 — culto amado.","vv. 9–10 — destino rejeitado.","vv. 11–12 — graça, firmeza e assembleia."]},
 {n:9,label:"Veja o desenho do Salmo inteiro",technical:"Macroestrutura",body:"Davi começa pedindo que Deus o examine e termina dentro da assembleia louvando. No meio, dois grupos são contrastados: companhia dos falsos e congregação do Senhor. A integridade não é solidão orgulhosa, mas lealdade que escolhe onde pertencer."},
 {n:10,label:"Note o que foge do padrão",technical:"Desvios significativos",body:"O contraste das mãos é especialmente eficaz: mãos lavadas junto ao altar versus mãos cheias de violência e suborno. O pedido ‘redime-me e tem compaixão’ no v. 11 também impede leitura meritória: até o homem que afirma integridade pede graça."},
 {n:11,label:"Resuma a mensagem em uma frase",technical:"Proposição",body:"A integridade pactual é uma vida sincera diante do exame de Deus, que recusa a comunhão com a falsidade, ama a adoração e ainda depende de redenção e graça para permanecer firme entre o povo do Senhor."},
 {n:12,label:"Coloque o Salmo no conjunto da Bíblia",technical:"Situação canônica e cristológica",body:"O Salmo 25 impede que o 26 seja lido como autojustificação. Cristo é o único homem cuja integridade é perfeita e que pode entrar no santuário por mérito próprio. O crente, justificado nele, pode ter consciência sincera de obediência real e ainda dizer ‘redime-me e tem compaixão de mim’. Essa combinação é profundamente reformada: justificação gratuita e santificação verdadeira.",items:["Não confundir integridade com impecabilidade.","Não usar graça para tornar irrelevante a escolha de companhias e práticas.","Toda firmeza cristã continua dependente de redenção."]}
 ],
 theology:["Sola fide não destrói a consciência de obediência sincera; apenas retira dela o mérito justificante.","Santidade inclui pertencimento comunitário e ética pública.","Culto verdadeiro e justiça cotidiana devem permanecer unidos.","Mesmo a integridade mais sincera pede misericórdia."],
 sermon:{idea:"A graça que nos redime também forma uma integridade que escolhe a verdade, ama o culto e permanece humilde diante do exame de Deus.",need:"Oscilamos entre orgulho moral e uma ideia de graça que trata obediência como irrelevante.",movements:[{title:"Viva aberto ao exame de Deus",vv:"vv. 1–3",point:"Integridade não teme que Deus veja o coração, mas também não reivindica perfeição."},{title:"Escolha suas comunhões",vv:"vv. 4–10",point:"Companhias, culto, mãos e dinheiro revelam lealdades."},{title:"Permaneça firme pela graça",vv:"vv. 11–12",point:"O homem íntegro ainda pede redenção e compaixão."}],climax:"‘Eu, porém, ando na minha integridade; livra-me e tem compaixão de mim’ (v. 11).",gospel:"A justiça perfeita é de Cristo; unidos a ele, somos aceitos gratuitamente e renovados para uma obediência real, ainda dependente de misericórdia.",applications:["submeter vida privada e pública ao exame de Deus","avaliar como companhias moldam fidelidade","rejeitar tanto perfeccionismo quanto graça barata"]}
},
"27":{
 titleVerse:true,
 sources:["Texto Massorético","Calvino, Comentário dos Salmos 1–35","A Medida do Louvor, salmos de confiança e lamento","teologia bíblica da presença de Deus"],
 steps:[
 {n:1,label:"Confira o texto que será estudado",technical:"Texto e variantes",body:"A sobrescrição o atribui a Davi. O salmo parece ter duas tonalidades muito diferentes: confiança forte nos vv. 1–6 e súplica angustiada nos vv. 7–14. Alguns intérpretes imaginaram duas composições, mas o mesmo vocabulário de inimigos, presença, casa, face e busca cria unidade suficiente para lê-lo como um único movimento de fé que inclui confiança e pedido."},
 {n:2,label:"Ouça o Salmo como poesia hebraica",technical:"Leitura e cantilação",body:"Ouça a segurança quase militar do início e depois a súbita oração ‘ouve, Senhor’. O contraste é a mensagem: confiança não elimina lamento. No final, o salmista fala consigo mesmo ou à comunidade: ‘espera no Senhor’."},
 {n:3,label:"Veja onde cada verso se divide",technical:"Cólons e acentos",body:"Quatro movimentos dão conta da unidade.",items:["vv. 1–3 — confiança diante do medo e dos inimigos.","vv. 4–6 — um desejo: habitar, contemplar e buscar Deus em seu santuário.","vv. 7–12 — oração por presença, direção e livramento.","vv. 13–14 — certeza de ver a bondade de Deus e chamado a esperar."]},
 {n:4,label:"Confirme se essas divisões fazem sentido",technical:"Sintaxe e paralelismo",body:"Os vv. 1–6 são declarativos e cheios de futuros confiantes. O v. 7 muda para imperativos: ‘ouve’, ‘tem compaixão’, ‘responde’. O v. 8 liga as duas partes pela palavra ‘face’: o coração responde ao chamado divino ‘buscai a minha face’. O final retorna à confiança com o verbo ‘espera’."},
 {n:5,label:"Observe o ritmo e as mudanças de tamanho",technical:"Escansão",body:"A diferença de tom entre as metades é mais importante que uma métrica média. A primeira é expansiva e afirmativa; a segunda tem súplicas mais curtas e urgentes. O v. 4 se destaca como concentração do desejo e o v. 14 como fecho repetitivo de espera e coragem."},
 {n:6,label:"Veja como uma linha responde à outra",technical:"Paralelismo",body:"O paralelismo une confiança, presença e petição.",items:["vv. 1–3: luz → salvação → fortaleza; inimigos atacam → tropeçam; exército acampa → coração não teme.","vv. 4–6: uma coisa pedir → morar → contemplar beleza → meditar no templo → ser escondido → oferecer sacrifícios de júbilo.","vv. 7–10: ouve → busca da face → não escondas a face → mesmo pai e mãe abandonando, o Senhor acolhe.","vv. 11–12: ensina o caminho → guia → não entregues à vontade dos adversários.","vv. 13–14: crer na bondade → esperar → ter coragem → esperar novamente."]},
 {n:7,label:"Perceba as repetições e imagens importantes",technical:"Recursos poéticos",body:"Luz, fortaleza, casa, beleza, face, caminho e espera são palavras-chave. O pedido ‘uma coisa’ reúne a multiplicidade de ameaças em um único desejo. A repetição de ‘espera no Senhor’ fecha o poema como disciplina da alma."},
 {n:8,label:"Separe os grandes blocos",technical:"Estrofes",body:"Quatro blocos são confirmados por mudança de função e vocabulário.",items:["vv. 1–3 — confiança.","vv. 4–6 — desejo da presença.","vv. 7–12 — lamento e petição.","vv. 13–14 — confiança renovada e espera."]},
 {n:9,label:"Veja o desenho do Salmo inteiro",technical:"Macroestrutura",body:"O poema mostra que confiança e lamento não são inimigos. O desejo do v. 4 e a busca da face no v. 8 ligam as duas metades. A estrutura é confiança → presença desejada → oração no perigo → espera. A fé madura sabe fazer todas as quatro coisas."},
 {n:10,label:"Note o que foge do padrão",technical:"Desvios significativos",body:"A virada abrupta no v. 7 é intencionalmente desconfortável: depois de dizer ‘não temerei’, Davi ainda precisa clamar. O v. 4 também se destaca como uma única prioridade em meio a muitos problemas. Essas mudanças impedem tanto triunfalismo quanto desespero."},
 {n:11,label:"Resuma a mensagem em uma frase",technical:"Proposição",body:"A confiança no Senhor não elimina a necessidade de pedir ajuda; ela concentra o coração na presença de Deus e transforma medo, abandono e falsos testemunhos em ocasião para buscar sua face e esperar sua bondade."},
 {n:12,label:"Coloque o Salmo no conjunto da Bíblia",technical:"Situação canônica e cristológica",body:"Este salmo é principalmente oração da igreja em Cristo. A casa e a face de Deus não devem ser alegorizadas detalhe por detalhe; a teologia bíblica mostra, porém, que por Cristo temos acesso à presença de Deus e aguardamos vê-lo plenamente. A espera cristã é sustentada pela obra já consumada do Mediador e pela esperança de sua presença final."}
 ],
 theology:["Fé e lamento podem coexistir na mesma oração.","A presença de Deus é o bem que organiza todos os outros pedidos.","Providência não exclui abandono humano, mas promete acolhimento divino.","Esperar no Senhor é atividade de fé, não passividade fatalista."],
 sermon:{idea:"A fé que diz ‘não temerei’ também sabe dizer ‘ouve-me’ e termina esperando porque deseja acima de tudo a presença de Deus.",need:"Confundimos fé com ausência de ansiedade e, quando ainda precisamos clamar, pensamos que nossa confiança era falsa.",movements:[{title:"Confesse quem Deus é diante do medo",vv:"vv. 1–3",point:"A identidade de Deus estabelece a base da coragem."},{title:"Dê um centro aos seus muitos desejos",vv:"vv. 4–6",point:"A presença de Deus é a ‘uma coisa’ que ordena o coração."},{title:"Clame e espere sem vergonha",vv:"vv. 7–14",point:"Confiança verdadeira inclui pedido, vulnerabilidade e perseverança."}],climax:"‘Uma coisa peço ao Senhor e a buscarei’ (v. 4), retomada em ‘buscai a minha face’ (v. 8).",gospel:"Por Cristo temos acesso à presença do Pai e a promessa de comunhão final; por isso podemos clamar no presente sem interpretar necessidade como rejeição.",applications:["não usar frases de confiança para silenciar lamento","reduzir desejos concorrentes à prioridade da presença de Deus","praticar espera ativa na Palavra e oração"]}
},
"28":{
 titleVerse:true,
 sources:["Texto Massorético","Calvino, Comentário dos Salmos 1–35","A Medida do Louvor, estrutura do lamento","teologia davídica do ungido e pastor"],
 steps:[
 {n:1,label:"Confira o texto que será estudado",technical:"Texto e variantes",body:"A sobrescrição o atribui a Davi. O salmo começa como lamento individual, contém pedido de juízo e termina em ação de graças que se amplia para o povo e o ungido. A linguagem imprecatória deve ser lida como recurso ao tribunal de Deus, não como autorização para vingança pessoal."},
 {n:2,label:"Ouça o Salmo como poesia hebraica",technical:"Leitura e cantilação",body:"Ouça a urgência de ‘não permaneças surdo’ e o medo de descer à cova. Depois, no v. 6, o tom muda: ‘bendito seja o Senhor, porque ouviu’. O salmo termina pedindo que Deus salve, abençoe, pastoreie e carregue seu povo."},
 {n:3,label:"Veja onde cada verso se divide",technical:"Cólons e acentos",body:"Quatro movimentos organizam a oração.",items:["vv. 1–2 — clamor para que Deus ouça.","vv. 3–5 — pedido para não ser tratado com os ímpios e para que Deus julgue suas obras.","vv. 6–7 — gratidão pela resposta e confiança do coração.","vv. 8–9 — ampliação para o povo, o ungido e o cuidado pastoral de Deus."]},
 {n:4,label:"Confirme se essas divisões fazem sentido",technical:"Sintaxe e paralelismo",body:"Os imperativos dominam os vv. 1–5. O v. 6 muda para perfeito: Deus ‘ouviu’ a voz da súplica. No v. 7, primeira pessoa descreve coração que confia e é ajudado. Nos vv. 8–9, pronomes e substantivos mudam para o povo e o ungido, ampliando a oração."},
 {n:5,label:"Observe o ritmo e as mudanças de tamanho",technical:"Escansão",body:"A súplica inicial é tensa e cumulativa. A virada para bênção no v. 6 cria sensação de alívio. O fecho usa uma sequência de imperativos comunitários — salva, abençoa, apascenta, exalta/carrega — que dá amplitude pastoral ao final."},
 {n:6,label:"Veja como uma linha responde à outra",technical:"Paralelismo",body:"Os pares acompanham a passagem de silêncio temido para ajuda recebida.",items:["vv. 1–2: se Deus ficar em silêncio → Davi se torna como os que descem à cova; clamor → mãos erguidas ao santuário.","vv. 3–5: ímpios falam paz e guardam mal no coração → pedido de retribuição segundo suas obras.","vv. 6–7: Deus ouviu → é força e escudo → coração confia → recebe ajuda → coração exulta → cântico agradece.","vv. 8–9: força do povo → refúgio do ungido → salvação → bênção → pastoreio → sustentação contínua."]},
 {n:7,label:"Perceba as repetições e imagens importantes",technical:"Recursos poéticos",body:"Rocha, cova, mãos, coração, escudo e pastor são imagens principais. A mão humana dos ímpios produz obras más; as mãos do suplicante se erguem; Deus age como força e escudo. O final troca linguagem de batalha por linguagem pastoral."},
 {n:8,label:"Separe os grandes blocos",technical:"Estrofes",body:"Quatro blocos se distinguem pela função.",items:["vv. 1–2 — pedido para ser ouvido.","vv. 3–5 — justiça contra o mal.","vv. 6–7 — resposta e gratidão.","vv. 8–9 — povo, ungido e pastoreio."]},
 {n:9,label:"Veja o desenho do Salmo inteiro",technical:"Macroestrutura",body:"O salmo começa com medo do silêncio de Deus e termina com Deus carregando seu povo. A resposta não fica privada: a experiência de Davi se expande para a comunidade e para o ungido. A oração individual torna-se teologia pastoral do povo da aliança."},
 {n:10,label:"Note o que foge do padrão",technical:"Desvios significativos",body:"A mudança do v. 6 é a virada decisiva, pois o mesmo salmista que temia silêncio agora afirma ter sido ouvido. O outro destaque é o v. 9, que acumula quatro pedidos comunitários e termina com imagem de pastor, alterando completamente o campo semântico."},
 {n:11,label:"Resuma a mensagem em uma frase",technical:"Proposição",body:"O crente pode entregar o mal ao juízo de Deus e clamar contra o silêncio, porque o Senhor ouve, fortalece e transforma o livramento individual em cuidado contínuo pelo seu povo e pelo seu ungido."},
 {n:12,label:"Coloque o Salmo no conjunto da Bíblia",technical:"Situação canônica e cristológica",body:"O ‘ungido’ e o tema pastoral pertencem ao mundo davídico e seguem a linha que culmina em Cristo, Rei e Pastor. A igreja não repete a guerra de Davi contra inimigos pessoais; ela entrega o juízo a Deus, ora por proteção e confia no Messias que salva e pastoreia seu povo.",items:["Imprecação é apelo judicial.","A resposta de Deus produz gratidão, não licença para revanche.","A experiência pessoal deve se abrir para intercessão pelo povo."]}
 ],
 theology:["O silêncio percebido de Deus não é ausência real de sua atenção.","Justiça divina desarma a vingança privada.","O Deus que salva também pastoreia e sustenta no tempo.","O ungido davídico prepara o caminho para Cristo."],
 sermon:{idea:"O Deus que parece silencioso ouve, julga com justiça e transforma o socorro recebido em cuidado para todo o seu povo.",need:"Diante do mal, queremos ou produzir nossa própria justiça ou concluir que Deus não está ouvindo.",movements:[{title:"Clame contra o silêncio",vv:"vv. 1–2",point:"A fé pode dizer a Deus que sua demora parece perigosa."},{title:"Entregue a justiça ao Juiz",vv:"vv. 3–5",point:"O salmista pede retribuição, não autorização para vingança."},{title:"Transforme resposta em louvor e intercessão",vv:"vv. 6–9",point:"O socorro pessoal se amplia para o povo e o Pastor-Rei."}],climax:"‘Bendito seja o Senhor, porque ouviu as minhas súplicas’ (v. 6).",gospel:"Cristo é o Ungido que sofreu injustiça, entregou-se ao justo Juiz e agora pastoreia e salva seu povo.",applications:["orar antes de reagir à injustiça","entregar retribuição a Deus","usar respostas recebidas para fortalecer e interceder pela comunidade"]}
},
"29":{
 titleVerse:true,
 sources:["A Medida do Louvor, cap. 27","Texto Massorético","Gênesis 6–9","Calvino, Comentário dos Salmos 1–35","contexto do Antigo Oriente Próximo usado apenas como iluminação comparativa"],
 steps:[
 {n:1,label:"Confira o texto que será estudado",technical:"Texto e variantes",body:"A sobrescrição o atribui a Davi. O hebraico dos vv. 1–2 usa linguagem antiga e a expressão ‘filhos dos poderosos/seres celestiais’. O contexto canônico mostra que esses seres são convocados a dar glória ao Senhor, nunca apresentados como rivais. O v. 10 usa mabbul, palavra ligada de modo especial ao Dilúvio de Gênesis."},
 {n:2,label:"Ouça o Salmo como poesia hebraica",technical:"Leitura e cantilação",body:"Ouça ‘a voz do Senhor’ repetida sete vezes na seção da tempestade. A tempestade começa sobre águas, atravessa montanhas, relâmpago e deserto e termina no templo com ‘Glória!’. Depois tudo se aquieta no trono e na palavra ‘paz’."},
 {n:3,label:"Veja onde cada verso se divide",technical:"Cólons e acentos",body:"Três movimentos são firmes.",items:["vv. 1–2 — convocação da corte celeste para dar glória e adorar.","vv. 3–9 — teofania da tempestade, marcada pelas sete ocorrências de ‘voz do Senhor’.","vv. 10–11 — o Senhor entronizado sobre o Dilúvio e abençoando seu povo com força e paz."]},
 {n:4,label:"Confirme se essas divisões fazem sentido",technical:"Sintaxe e paralelismo",body:"Os vv. 1–2 usam imperativos ‘dai’ e ‘adorai’. Os vv. 3–9 mudam para declarações sobre a voz divina. Os vv. 10–11 abandonam a descrição da tempestade e apresentam o Senhor sentado como Rei, seguido de dois futuros: dará força e abençoará com paz."},
 {n:5,label:"Observe o ritmo e as mudanças de tamanho",technical:"Escansão",body:"O salmo é majoritariamente equilibrado, mas o v. 7 é um monocolo: ‘a voz do Senhor despede chamas de fogo’. Dentro da sequência de sete ‘vozes’, essa linha central e isolada imita o relâmpago. A forma e o fenômeno descrito convergem de maneira forte.",items:["Os vv. 1–2 formam uma escada de imperativos que termina em adoração.","A tempestade se move geograficamente do mar e norte para o deserto ao sul.","O fecho substitui ruído por trono, força e paz."]},
 {n:6,label:"Veja como uma linha responde à outra",technical:"Paralelismo",body:"A repetição avança em vez de ficar parada.",items:["vv. 1–2: dai glória e força → dai glória ao nome → adorai; cada degrau aproxima da adoração.","v. 3: voz sobre águas → Deus da glória troveja → Senhor sobre muitas águas.","v. 4: voz em poder → voz em majestade.","vv. 5–6: quebra cedros → despedaça cedros do Líbano → montanhas saltam.","v. 7: relâmpago isolado.","vv. 8–9: deserto treme → animais e florestas respondem → templo diz ‘Glória’.","vv. 10–11: Rei sobre o Dilúvio → Rei para sempre → força ao povo → paz ao povo."]},
 {n:7,label:"Perceba as repetições e imagens importantes",technical:"Recursos poéticos",body:"‘Voz do Senhor’ é a grande anáfora. Cedros, Líbano, Siriom, fogo, deserto, corças e florestas fazem a criação inteira responder. O poema usa linguagem que o mundo cananeu associava à tempestade para confessar que esse poder pertence a YHWH. A comparação histórica ilumina; o próprio cânon decide o sentido."},
 {n:8,label:"Separe os grandes blocos",technical:"Estrofes",body:"Três blocos são confirmados por cenário, forma verbal e repetição.",items:["vv. 1–2 — corte celeste e adoração.","vv. 3–9 — tempestade e sete vozes.","vv. 10–11 — trono, povo e bênção."]},
 {n:9,label:"Veja o desenho do Salmo inteiro",technical:"Macroestrutura",body:"A tempestade é cercada por culto e reino. Ela não é caos fora do controle; o Senhor está sobre as águas e se assenta como Rei sobre o Dilúvio. O poder cósmico termina dirigido ao bem do povo: força e paz."},
 {n:10,label:"Note o que foge do padrão",technical:"Desvios significativos",body:"O monocolo do v. 7 é o desvio formal mais forte e coincide com o relâmpago, por isso merece interpretação. O outro grande contraste é o v. 11: depois de cedros quebrados e desertos tremendo, a última palavra temática é paz. Poder e cuidado pactual pertencem ao mesmo Rei."},
 {n:11,label:"Resuma a mensagem em uma frase",technical:"Proposição",body:"A tempestade que parece encarnar caos e poder indomável é, do começo ao fim, governada pela voz do Senhor, o Rei que domina as águas e usa seu poder não apenas para abalar a criação, mas para dar força e paz ao seu povo."},
 {n:12,label:"Coloque o Salmo no conjunto da Bíblia",technical:"Situação canônica e cristológica",body:"O v. 10 deve ser iluminado primeiro por Gênesis 6–9: mabbul liga o trono de Deus ao Dilúvio. A comparação com Baal ajuda a perceber a polêmica cultural, mas não controla a exegese. Cristologicamente, a igreja adora em Cristo o Senhor soberano da criação; os Evangelhos também mostram Jesus exercendo autoridade sobre tempestades, mas não precisamos transformar o salmo em previsão direta desse episódio.",items:["Cânon antes de paralelos pagãos.","Não tratar mitologia comparada como fonte do conteúdo revelado.","O poder do Rei termina em bênção pactual, não em espetáculo."]}
 ],
 theology:["Deus governa forças que o ser humano experimenta como caos.","A criação não é divina; ela responde à voz do Criador.","A revelação pode usar vocabulário cultural e ao mesmo tempo corrigi-lo polemicamente.","Poder soberano e paz pactual não são atributos concorrentes."],
 sermon:{idea:"A voz que domina o caos é a mesma que abençoa o povo com paz.",need:"Tememos forças que parecem fora do controle e, ao mesmo tempo, somos tentados a admirar poder sem perguntar para que ele serve.",movements:[{title:"Dê a glória ao verdadeiro Senhor",vv:"vv. 1–2",point:"Toda autoridade celeste é chamada a adorar, não a competir."},{title:"Ouça a voz atravessar a tempestade",vv:"vv. 3–9",point:"Mar, montanha, fogo e deserto estão sob comando."},{title:"Veja o Rei acima do caos e perto do povo",vv:"vv. 10–11",point:"O poder que reina termina dando força e paz."}],climax:"O v. 10: o Senhor se assenta como Rei sobre o Dilúvio.",gospel:"Em Cristo vemos a soberania de Deus entrar em nosso caos sem perder o controle e conduzir seu povo à paz com Deus e à paz final do reino.",applications:["submeter medos cósmicos e históricos ao governo de Deus","recusar idolatria de poder","usar autoridade recebida para servir e promover paz justa"]}
},
"30":{
 titleVerse:true,
 sources:["Texto Massorético","Calvino, Comentário dos Salmos 1–35","NET Bible Notes","A Medida do Louvor, gênero de ação de graças"],
 steps:[
 {n:1,label:"Confira o texto que será estudado",technical:"Texto e variantes",body:"A sobrescrição chama o poema de ‘cântico para a dedicação da casa’ e o atribui a Davi. Como o templo foi construído depois de Davi, a referência pode ser à casa/palácio, a uma composição destinada a uso futuro ou a reutilização litúrgica posterior; o texto não permite escolher com certeza. A mensagem do corpo do salmo é clara: livramento de ameaça mortal, disciplina, autoconfiança exposta e louvor restaurado."},
 {n:2,label:"Ouça o Salmo como poesia hebraica",technical:"Leitura e cantilação",body:"Ouça a repetição de reversões: descer/subir, ira/favor, choro/alegria, segurança/rosto escondido, pranto/dança, lamento/louvor. O poema inteiro se move por contrastes que mostram a mão de Deus transformando a situação."},
 {n:3,label:"Veja onde cada verso se divide",technical:"Cólons e acentos",body:"Cinco movimentos explicam o salmo.",items:["vv. 1–3 — gratidão por ter sido levantado da proximidade da morte.","vv. 4–5 — convite à comunidade: cantar porque a ira é breve e o favor é duradouro.","vv. 6–7 — confissão de autoconfiança e experiência do rosto de Deus escondido.","vv. 8–10 — oração e argumento: que proveito haverá se eu descer ao pó?","vv. 11–12 — reversão final: pranto em dança, pano de luto retirado e louvor sem silêncio."]},
 {n:4,label:"Confirme se essas divisões fazem sentido",technical:"Sintaxe e paralelismo",body:"Os verbos iniciais estão no passado de gratidão: Deus levantou, curou e fez subir. Os vv. 4–5 mudam para imperativos comunitários. O v. 6 introduz fala passada do próprio salmista: ‘jamais serei abalado’, revelando falsa segurança. Os vv. 8–10 registram o clamor, e os vv. 11–12 retornam ao passado de reversão e ao propósito de louvar."},
 {n:5,label:"Observe o ritmo e as mudanças de tamanho",technical:"Escansão",body:"A forma é marcada por pares antitéticos. O peso não está em um metro fixo, mas nas reversões concentradas. O v. 5 é especialmente memorável por comprimir ira/favor e noite/manhã. Os vv. 11–12 expandem a reversão em cadeia, levando do luto ao louvor permanente."},
 {n:6,label:"Veja como uma linha responde à outra",technical:"Paralelismo",body:"O paralelismo é dominado por contraste e transformação.",items:["vv. 1–3: inimigos não triunfam → Deus cura → faz subir do Sheol/cova.","vv. 4–5: cantar e agradecer → ira momentânea/favor duradouro → choro à noite/alegria pela manhã.","vv. 6–7: ‘não serei abalado’ → estabilidade era favor de Deus → rosto escondido → perturbação.","vv. 8–10: clamor → pergunta sobre o pó louvar → pedido de misericórdia e ajuda.","vv. 11–12: pranto → dança; luto → alegria; silêncio → louvor."]},
 {n:7,label:"Perceba as repetições e imagens importantes",technical:"Recursos poéticos",body:"Cova, noite, manhã, monte, rosto, pó, pano de luto e dança criam uma sequência de descida e subida. O início ‘tu me elevaste’ usa imagem de tirar água de um poço, adequada à experiência de alguém trazido de volta da beira da morte."},
 {n:8,label:"Separe os grandes blocos",technical:"Estrofes",body:"Cinco blocos são confirmados por mudança de pessoa e função.",items:["vv. 1–3 — testemunho de livramento.","vv. 4–5 — convite ao louvor.","vv. 6–7 — confissão de autossuficiência corrigida.","vv. 8–10 — oração no perigo.","vv. 11–12 — reversão e voto de louvor."]},
 {n:9,label:"Veja o desenho do Salmo inteiro",technical:"Macroestrutura",body:"O salmo é uma narrativa de reversões. No centro, Davi reconhece que havia confundido a estabilidade dada por Deus com uma estabilidade que lhe pertencia. Quando o rosto de Deus se esconde, sua autoconfiança desaba. O livramento devolve a dádiva ao Doador e transforma vida preservada em louvor."},
 {n:10,label:"Note o que foge do padrão",technical:"Desvios significativos",body:"A confissão do v. 6 é a chave interpretativa: ‘na minha prosperidade eu dizia: jamais serei abalado’. Ela impede transformar o salmo em simples promessa de que toda tristeza terminará rapidamente. O tema é disciplina graciosa que destrói autossuficiência e restaura louvor. O v. 11 fornece a grande reversão final."},
 {n:11,label:"Resuma a mensagem em uma frase",technical:"Proposição",body:"Deus pode usar disciplina e ameaça de perda para expor uma segurança autossuficiente, mas seu favor levanta o dependente, transforma luto em louvor e devolve a vida ao propósito de agradecer ao Senhor."},
 {n:12,label:"Coloque o Salmo no conjunto da Bíblia",technical:"Situação canônica e cristológica",body:"O movimento morte–vida pode ser lido tipologicamente à luz da ressurreição, mas o salmo não é uma previsão direta da ressurreição de Jesus. Em Cristo, porém, a vitória definitiva sobre a morte garante que as reversões temporais da providência apontam para uma reversão final. Também devemos resistir a uma aplicação simplista de ‘choro à noite, alegria pela manhã’ como promessa de resolução rápida de toda dor nesta vida.",items:["Disciplina paternal não é condenação para quem está em Cristo.","Prosperidade pode revelar falsa autonomia.","A esperança final é ressurreição e louvor, mesmo quando algumas dores permanecem até a morte."]}
 ],
 theology:["Providência inclui tanto favor percebido quanto disciplina que desmonta autoconfiança.","Prosperidade não é prova de autossuficiência nem direito adquirido.","Louvor é propósito do livramento, não mero sentimento posterior.","A ressurreição de Cristo dá horizonte final às reversões incompletas desta vida."],
 sermon:{idea:"Deus transforma a segurança em si mesmo em dependência e usa o livramento para devolver nossa voz ao louvor.",need:"Recebemos estabilidade como dádiva e logo começamos a tratá-la como propriedade garantida por nossa competência.",movements:[{title:"Lembre quem o levantou",vv:"vv. 1–5",point:"Livramento e alegria são dádivas que chamam a comunidade ao louvor."},{title:"Confesse a falsa segurança",vv:"vv. 6–10",point:"Prosperidade pode esconder dependência até que Deus exponha a fragilidade."},{title:"Transforme vida preservada em louvor",vv:"vv. 11–12",point:"A reversão final não termina em conforto, mas em adoração."}],climax:"‘Quanto a mim, dizia eu na minha prosperidade: jamais serei abalado’ (v. 6), corrigido por ‘tu escondeste o rosto, e eu fiquei perturbado’ (v. 7).",gospel:"A ressurreição de Cristo garante que a última palavra para os que estão nele não será a cova, e sua graça transforma disciplina presente em preparação para louvor eterno.",applications:["reconhecer prosperidade como graça e não direito","deixar a disciplina expor autossuficiência","usar livramentos para testemunho e adoração, não para voltar à independência"]}
}
});
